### ISSUE TITLE
Testing new dependecy resolver in Pip 20.2

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#1028]
There is a new dependency resolver in Pip 20.2 implementing greater strictness. We need to test the resolver and our dependencies. This could cause significant issues if we find new incompatibilities in libraries.

See: https://pip.pypa.io/en/latest/user_guide/#changes-to-the-pip-dependency-resolver-in-20-2-2020.

**Comment by davidpofo** [comment]
After investigating the new dependency resolver there are no issues installing our current requirements with the new dependency resolver coming as a default in pip 20.3.
