### ISSUE TITLE
Yum Packages Not Updated Per Security Scans

### ISSUE THREAD

**Issue by bama4** [GovReady/govready-q#1047]
**Description**
The command `yum --upgrade` is not being run in the Dockerfile for Govready-q.
This results in numerous outdated packages to be installed in the docker container when created.

**Risk Level**
In the Twistlock findings, the risk levels for these issues were labeled as Moderate, Low, and Important. These issues can all easily be fixed by adding `yum upgrade` after the `yum install --update` command in the Dockerfile.

Some other outdated version issues can be fixed by updating the versions downloaded in the govready repository scripts.

**Goal**
- [ ] Add `yum install --upgrade` to Dockerfile

Ensure that the following yum packages meet the following conditions:

- [ ] `curl` is a version greater than `7.65.3`
- [ ] `libssh2` is a version greater than `1.9.0`
- [ ] `cairo` is a version greater than `1.15.14`
- [ ] `nss`
- [ ] `libxml2` is a version greater than `2.9.10`
- [ ] `libX11` is a version greater than `1.6.10`
- [ ] `lcm2` is a version greater than `2.9`
- [ ] `python3` is a version greater than `3.8.3`
- [ ] `cpio` is a version greater than `2.13`
- [ ] `libcroco` is a version greater than `0.6.13`
- [ ] `openldap` is a version greater than `2.4.50`
- [ ] `python 2.7.5` is removed
- [ ] `systemd` is a version greater than `243`
- [ ] `expat` is a version greater than `2.2.8`
- [ ] `openssh` is a version greater than `8.3`
- [ ] `pcre` is a version greater than `8.44`
- [ ] `bash` is a version greater than `5.0`
- [ ] `glibc` is a version greater than `2.31`
- [ ] `dbus` is a version greater than `1.12.18`
- [ ] `dbus-libs` is a version greater than `1.12.8`

Ensure that the following Django and web packages meet the following conditions:

- [ ] JQuery used is version greater than or equal to `3.5.0`

**Comment by bama4** [comment]
Discovered that these packages are already at their latest versions that are listed in the Centos 7 packages http://mirror.centos.org/centos/7/os/x86_64/Packages/.
Packages such as curl for example not being up to date is a well known issue that is actively being worked on:

https://access.redhat.com/discussions/4966381

**Comment by bama4** [comment]
Discovered that these packages are already at their latest versions that are listed in the Centos 7 packages http://mirror.centos.org/centos/7/os/x86_64/Packages/.
Packages such as curl for example not being up to date is a well known issue that is actively being worked on:

https://access.redhat.com/discussions/4966381

**Comment by bama4** [comment]
@davidpofo If we are switching to Ubuntu for the Docker image, it sounds like this is not a concern.

**Comment by davidpofo** [comment]
> @davidpofo If we are switching to Ubuntu for the Docker image, it sounds like this is not a concern.

@bama4 sounds right to me. @peterkaminski Anything to add?

**Comment by peterkaminski** [comment]
@davidpofo @bama4, yes, it sounds like this is not a concern for now.
