### ISSUE TITLE
Limit The Type of Discussion Attachments Allowed

### ISSUE THREAD

**Issue by bama4** [GovReady/govready-q#1057]
**Description**
The type of attachments that can be uploaded to a discussion ~or a question~ is not being limited. This could pose as a security risk. This does not completely eliminate the risk but does reduce the changes of a malicious user executing an arbitrary file on the system if there are other vulnerabilities present.

Note: uploads for questions will be handled in a separate ticket.

**Risk Level**
Risk Level is Medium in Fortify.

**Source**
https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload

**Goal**
- [x] Limit the type of attachments in the discussion pages, and check file type matches extension.

**Comment by davidpofo** [comment]
@bama4 Could you point me to where the question pages create attachments outside of the discussions django app. I added a validator to discussions to address the discussion pages issue and arbitrarily chose pdf, doc, and docx as file extensions to keep. https://github.com/GovReady/govready-q/pull/1060

**Comment by bama4** [comment]
> @bama4 Could you point me to where the question pages create attachments outside of the discussions django app. I added a validator to discussions to address the discussion pages issue and arbitrarily chose pdf, doc, and docx as file extensions to keep. #1060

@davidpofo Thanks,
This was an error, there only appears to be one place where attachments are uploaded.

**Comment by bama4** [comment]
> @bama4 Could you point me to where the question pages create attachments outside of the discussions django app. I added a validator to discussions to address the discussion pages issue and arbitrarily chose pdf, doc, and docx as file extensions to keep. #1060

Update on this, I see that it is possible to upload files as answers to questions as shown in https://github.com/GovReady/govready-q/blob/master/guidedmodules/answer_validation.py#L28

and https://github.com/GovReady/govready-q/blob/master/templates/question.html#L391

Investigating this further, it allows me to send file answers, but fails due to the form not allowing blank answers.

Is it possible for someone to create their own questionnaire and upload it to the server? If it is possible then:
- There could be a potential file upload issue here as it does not appear that file uploads are checked here.
- Another ticket may need to be created to address the file uploads when the questionnaire answers are allowed to be files

**Comment by davidpofo** [comment]
@bama4 Where is that question coming from that you have above? Also yes, anyone with ability to make appsources (the yaml that holds the questionnaires) can introduce them to the project. From there, any questions are incorporated into their version of GovReady.

**Comment by bama4** [comment]
> @bama4 Where is that question coming from that you have above? Also yes, anyone with ability to make appsources (the yaml that holds the questionnaires) can introduce them to the project. From there, any questions are incorporated into their version of GovReady.

It is one of the built-in default questions.
I changed the input type in the form on my browser to be able to send file type HTTP payloads.

It accepts the HTTP file payload as a valid submission but does not place the file to the database on the govready server, however, only because the answer field check for an empty answer failed. 

One way to handle this may be similar to what was done for the discussion attachments:
- Support a limited range of file types (pdf,  png, jpeg) for custom questionnaire answers.
