### ISSUE TITLE
Need more automated testing for validating uploaded files

### ISSUE THREAD

**Issue by davidpofo** [GovReady/govready-q#1082]
Files uploaded for as question answers or comment attachments need a broader suite of tests to cover the various file types.

**Comment by bama4** [comment]
Potential Tests:
- Unsupported HTTP requests:
- [ ] Test that unsupported file with valid content type and valid extension is rejected
- [ ] Test that supported file  with invalid content type and valid extension is rejected
- [ ] Test that jpeg file with mixmatch content type and valid extension is rejected
- [ ] Test that png file with mixmatch content type and valid extension is rejected
- [ ] Test that pdf file with mixmatch content type and valid extension is rejected

- Supported HTTP requests, valid extensions
- [ ] Test that jpeg file with matching content type and valid extension is accepted
- [ ] Test that png file with matching content type and valid extension is accepted
- [ ] Test that pdf file with matching content type and valid extension is accepted

- Supported HTTP request, invalid extensions
- [ ] Test that jpeg file with matching content type and invalid extension is rejected
- [ ] Test that png file with matching content type and invalid extension is rejected
- [ ] Test that pdf file with matching content type and invalid extension is rejected

For more testing ideas, see https://owasp.org/www-community/vulnerabilities/Unrestricted_File_Upload.

At the least we may want to test that:
- [ ] Test that the file with the same name is uploaded
- [ ] Test that the file contains special characters (such as '\' or '.')

**Comment by bama4** [comment]
@davidpofo Is this ticket already being worked on? If not, I can take this ticket for adding onto the tests

**Comment by gregelin** [comment]
Fixed
