### ISSUE TITLE
Issues installing govready with Mariadb

### ISSUE THREAD

**Issue by davidpofo** [GovReady/govready-q#1084]
As a user, when I am installing govready on my centos8 OS I should be able to follow along with the documentation for setting up a MariaDB database. Currently, there is a hole in the current set of commands provided in setting up a mysql database for govready.

**Comment by gregelin** [comment]
@davidpofo Do we feel we've addressed this issue?

**Comment by gregelin** [comment]
@davidpofo Also related issu #910

**Comment by davidpofo** [comment]
> @davidpofo Also related issue #910

Yes ready to close. I merged the mariadb instructions in[ govready-q-docs ](https://github.com/GovReady/govready-q-docs/pull/20)
