### ISSUE TITLE
WORKAROUND: Commonmark is not updated for python 3.9 

### ISSUE THREAD

**Issue by kerryrm** [GovReady/govready-q#1085]
Two files in the Commonmark module (common.py, inlines.py) need to be edited as python3.9 removed html.parser.HTMLParser.unescape().

` HTMLunescape = html.parser.HTMLParser().unescape `

becomes  

`HTMLunescape = html.unescape.`

**Comment by tirkarthi** [comment]
Seems to be fixed upstream in https://github.com/readthedocs/commonmark.py/commit/e2f389456b39aece2d9ced16f3a3656caeb0a423

**Comment by gregelin** [comment]
Closed by #1375
