### ISSUE TITLE
DOCUMENTATION Update: remove "host" option from Environment.json

### ISSUE THREAD

**Issue by kerryrm** [GovReady/govready-q#1086]
[Here](https://govready-q.readthedocs.io/en/latest/installation-and-setup/desktop-installation/macos.html)
Within the section 
Creating “environment.json” configuration file
it says
"host": "localhost:8000",
error says:
WARNING: Use of 'host' environment parameter deprecated. Please use 'govready-url' environment parameter in future.
switch to 
  "govready-url": "http://localhost:8000",

**Comment by kerryrm** [comment]
It appears this has been updated for CentOS, but MacOS documentation is out of sync.

**Comment by peterkaminski** [comment]
Thanks, Kerry.

This issue should get moved over to the [govready-q-docs](https://github.com/GovReady/govready-q-docs/issues) issues when someone gets a round tuit, at which point it can probably be closed in this repo.

**Comment by kerryrm** [comment]
My bad. Sorry about the misplacing.

**Comment by peterkaminski** [comment]
A bug report in hand (no matter what repo) is worth two in the ether...
