### ISSUE TITLE
Fix the Fortify Password Management: Hardcoded Password False Positives

### ISSUE THREAD

**Issue by bama4** [GovReady/govready-q#1097]
**Description**

To avoid having to explain future Fortify issues that are false positive. The preferable solution is to fix some of the false positive findings such that they will not appear in future Fortify runs.

This ticket is for fixing the false positives under the `Fortify Password Management: Hardcoded Password` category.

**Goal**
- [ ] Fix all of the false positives that can be changed that fall under the `Fortify Password Management: Hardcoded Password` category.

**Code Practice Suggestions**
In the future, avoid using variables containing the word `PASSWORD`.

**Comment by gregelin** [comment]
@bama4 Can we close this issue? Why is issue blocked?

**Comment by bama4** [comment]
Finished, findings either explained or fixed
