### ISSUE TITLE
Update Docker Base Image to Centos 7.9.2009

### ISSUE THREAD

**Issue by bama4** [GovReady/govready-q#1117]
**Description**

The latest docker image for Centos 7 is `centos 7.9.2009`.
This ticket updates the docker image to the latest (`centos 7.9.2009`)

**Goal**
- [x] Update docker base image from `centos7.8.2003` to `centos 7.9.2009`.

**Comment by gregelin** [comment]
Upgrading base image to Ubuntu 18.04 or higher.
