### ISSUE TITLE
Fix Insecure Randomness False Positive Findings

### ISSUE THREAD

**Issue by bama4** [GovReady/govready-q#1126]
**Description**

To avoid having to explain future Fortify issues that are false positive or simply a bad practice. The preferable solution is to fix some of the false positive findings such that they will not appear in future Fortify runs.

This ticket is for fixing the false positives under the `Insecure Randomness` category.

In this case, the insecure random generator is either being used in testing or in a non-cryptographic context.

**Risk Level**

Fortify lists this issue as a Critical risk, however, no instances are being used in a cryptographic context outside of test code.

**Goal**
- [x] Fix all of the bad practice issues that can be changed that fall under the `Insecure Randomness` category.

**Code Practice Suggestions**
Use the `secrets` module for generating cryptographically strong random numbers https://docs.python.org/3/library/secrets.html as suggested in https://docs.python.org/3/library/random.html

**Comment by gregelin** [comment]
Fixed.
