### ISSUE TITLE
Allow admins to edit the description of a system component

### ISSUE THREAD

**Issue by t-s** [GovReady/govready-q#1132]
**Story:**
As a GovReady administrator, I need the ability to edit the description of a component, and to be able to do it in a user friendly way. 

**Developer hints:**
This could be done either with an in-place editor, or a pop-up dialog. Either method could and likely should allow the administrative user to use rich text to fully describe the component. Several tools are available to assist with this implementation.

See below reference links for such tools.

**Acceptance Criteria:**

GIVEN I have GovReady admin privileges,
WHEN I am on the component detail page for a component in the component library,
THEN I am able to take an action that will update the description for said component - either by clicking in the textarea, or by clicking a button that produces a dialog that allows me to affect changes to the description and choose to save or not to save, with a confirmation dialog.

GIVEN I have GovReady admin privileges,
WHEN I am on the component detail page for a component in the component library,
WHEN I have begun editing the description of the component,
WHEN I am prepared to save changes,
THEN I am able to confirm my changes with a confirmation dialog.

GIVEN I have GovReady admin privileges,
and GIVEN I have taken action to make a change to the description,
WHEN I save the change,
THEN the description of the component is changed in the database,
AND the description change is logged using the existing logger infrastructure,
AND the description updates without a page refresh on the web page I am viewing.

A simple unit test is written to ensure proper updating of the description of a component asserting the above criteria.

A simple UI test is written to test the existence of the clickable action on the component page to begin to edit the description, either by clicking the textarea or spawning a popup dialog, if the user is an admin.

**Notes:**

Work is to be done as part of a feature branch.

Related to #1130.

***Referenced links***
- [Quill.js](https://quilljs.com/) - Quill has been previously implemented and is currently fetched when pulling vendor resources
- [Stackedit, a Markdown editor](https://stackedit.io/)
- [medium-editor, an open-source clone of the editor medium.com uses](https://yabwe.github.io/medium-editor/)
- [Pell, notable for no dependencies](https://jaredreich.com/pell/)

**Comment by gregelin** [comment]
Completed
