### ISSUE TITLE
Improvements to testmocking for larger scale testing

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#1137]
The purpose of this story is to improve the existing `testmocking` Django app to support larger scale testing.

As GovReady developer, I want to be able to automatically populate the database with thousands of users and hundreds of projects/systems, so that I can properly load test GovReady and make sure the architecture works at scale.

Goal (essential):
- [x] Rename `testmocking` to `loadtesting`
- [x] Make sure everything works with latest version of GovReady-Q
- [x] Support loading at least 2,000 users
- [x] Support creating 400 projects/systems
- [ ] Support adding components and controls (new feature in more recent version of GovReady)

Goal (better):
- [ ] Support creating 1500 POA&Ms

**Comment by HeatherSoron** [comment]
At this scale, it looks like I'll need to switch off of web-based project/system creation, and probably go directly through the model layer. That's not surprising, and we do have existing code which does it for users. When I tried adapting the web-based project/system code, I noticed that requests were being processed _very_ slowly, hence the "ah." moment. Additional benefit: less chance of this codepath breaking when changes in the presentation layer occur.

Speaking of slow processing, I noticed that with 2000 users, `GET /projects` takes around 4.5s on my dev environment for the request to complete. I imagine that would get noticed again later as well, but I figured I'd comment on it now before I forget.

**Comment by peterkaminski** [comment]
> I noticed that with 2000 users, `GET /projects` takes around 4.5s on my dev environment for the request to complete

Good observation.  I'm working with a group using the system, and they have many users, and it runs slowly for them.  I'm eager to start to figure out why.

**Comment by HeatherSoron** [comment]
@peterkaminski Would you want me to pass along easy repro steps, when/if I come across issues like this? (and as I get the applicable cli commands updated for the current application code)

**Comment by gregelin** [comment]
Related PR #1236 merged into develop.

**Comment by gregelin** [comment]
Fixed
