### ISSUE TITLE
Create govready-q-test Repository and Add as a Submodule

### ISSUE THREAD

**Issue by bama4** [GovReady/govready-q#1200]
**Describe the issue as a Story**

**NOTE** This issue needs to be discussed as a team.

As a developer of GovReady, I would like to have govready local tests under a single directory structure as a submodule of the main govready-q repository.

The purpose of this change is to avoid unnecessary false positives in the test code when running code scans.

The name of the new test repository is `govready-q-test`. The directory structure of `govready-q-test` should mirror `govready-q` except `govready-q-test` contains test code and fixtures only.

Example:

```
# Code Repo
govready-q
    |____ tests (cf445c) # submodule commit hash
    |____ discussion
                |____ admin.py
                |____ models.py
                |____ urls.py
                |____ views.py

# Test Repo
govready-q-test
    |____ discussion
                |____ tests.py
```

The govready-q test repository would not be released in production.

The repository would be `Govready/govready-q-test`.

**To Reproduce**
See Fortify warnings on test code that is not a security concern.

**Expected behavior**
When running `python3 manage.py test` in `govready-q`,
this should trigger running tests in the `tests` folder in `govready-q`.
The `tests` folder in `govready-q` is the submodule repo `govready-q-test`.

When a new feature is pushed to `govready-q`, the unit tests should be written in the appropriate folder in `govready-q-test`

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A

## Developer hints

See example directory structure

## Acceptance criteria 

  GIVEN a feature with additional unit tests,
  WHEN the feature is ready to be merged into `develop`,
  THEN there is a pull request open for adding the source code changes to the `govready-q` repo,
             and a pull request up for the unit test changes to be added to the `govready-q-test` repo.

**Additional context**
N/A

**Comment by davidpofo** [comment]
I am not sure if this is really gaining us anything. I appreciate tests separated into their respective Django apps/directories and being able to run them by Django app, specific functions within those apps, and finally the full test suite. `python3 manage.py test` already starts all tests created in govready-q(the respective tests.py for each Django app)

**Comment by bama4** [comment]
Updated the description

**Comment by bama4** [comment]
This ticket was created to address the idea that the test files should be removed from the GovReady library due to security scans. The problem of false positives in test (for Fortify at least) may be resolved once we have the .fpr files to handle these false positives.

**Comment by davidpofo** [comment]
> This ticket was created to address the idea that the test files should be removed from the GovReady repository due to false positives in security scans. The problem of false positives in tests (for Fortify at least) may be resolved once we have the .fpr files to handle these false positives.

I am not sure about this and would love for your input but one solution that is a middle-ground is trying to use a different test layout. For example pytest it is good practice to structure the govready-q repository like so:

 `# Code Repo
govready-q
    |____ discussion
                |____ test
                         |____ tests.py
                |____ admin.py
                |____ models.py
                |____ urls.py
                |____ views.py
`
Here are some more examples for the [test layouts](https://docs.pytest.org/en/stable/goodpractices.html) possible.

**Comment by gregelin** [comment]
I think the right solution is having Fortify ignore the test files.
