### ISSUE TITLE
Dependency Error When Downloading Pip requirements

### ISSUE THREAD

**Issue by bama4** [GovReady/govready-q#1206]
**Describe the bug as a Story**
An error occurs when running any script that downloads the pip dependencies in the `develop` branch. This includes the `quickstart.sh` script as well as when building docker containers.

**To Reproduce**
1. Create a clean python3 virtual environment (`python3 -m venv env`)
2. Run `./quickstart.sh`
2. See pip error:
```
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata==3.3.0->-r requirements.txt (line 307))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=3.6.4; python_version < "3.8" from https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl#sha256=7cb407020f00f7bfc3cb3e7881628838e69d8f3fcab2f64742a5e76b2f841918 (from importlib-metadata==3.3.0->-r requirements.txt (line 307))
```

**Expected behavior**
When I run `quickstart.sh` and build docker containers, pip should download and install all dependencies without issue.

**Screenshots**
```
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata==3.3.0->-r requirements.txt (line 307))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=3.6.4; python_version < "3.8" from https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl#sha256=7cb407020f00f7bfc3cb3e7881628838e69d8f3fcab2f64742a5e76b2f841918 (from importlib-metadata==3.3.0->-r requirements.txt (line 307))
```

**Desktop (please complete the following information):**
 - OS: Ubuntu 18.04
 - Browser [e.g. chrome, safari]: N/A
 - Virtual Machine? Yes
 - Screen size
 - Python Version: 3.6.9, 3.8
 - pip version: pip 20.3.3 
 - Python Virtual Environment? Yes

## Acceptance criteria 

  GIVEN a clean python virtual environment or docker build,
  WHEN `pip3 install -r requirements.txt` or similar is run,
  THEN all the python packages in `requirements.txt` should install correctly

**Additional context**
Other pip users are having similar issues:
https://github.com/actions/virtual-environments/issues/2245
https://github.com/cjolowicz/hypermodern-python/issues/174

**Comment by davidpofo** [comment]
@bama4 could you try installing the requirements with install-govready-q.sh instead of quick-start.sh I haven't had problems with the former and should get the user everything they need to use govready(including the pip packages)

**Comment by bama4** [comment]
@davidpofo What version of python are you using?
I am still getting the same error when using the `install-govready-q.sh` script.
```
Collecting typing-extensions>=3.6.4; python_version < "3.8" (from importlib-metadata==3.3.0->-r requirements.txt (line 307))
In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
    typing-extensions>=3.6.4; python_version < "3.8" from https://files.pythonhosted.org/packages/60/7a/e881b5abb54db0e6e671ab088d079c57ce54e8a01a3ca443f561ccadb37e/typing_extensions-3.7.4.3-py3-none-any.whl#sha256=7cb407020f00f7bfc3cb3e7881628838e69d8f3fcab2f64742a5e76b2f841918 (from importlib-metadata==3.3.0->-r requirements.txt (line 307))
```

**Comment by davidpofo** [comment]
@bama4 Python 3.8.2. If you are using the scripts off of the up-to-date requirements this is shouldn't be the install scripts(saying this after using them this morning branching off of develop).

**Comment by bama4** [comment]
Tried installing `import-metadata` on its own after clearing pip cache from desktop and the issue persists. It appears to be an issue external to govready.
