### ISSUE TITLE
OSCAL XML SSP File Export Begins with Whitespace

### ISSUE THREAD

**Issue by ohsh6o** [GovReady/govready-q#1209]
**Describe the bug as a Story**
Current releases of develop being deployed to test.govready.com with example projects with a System Security Plan are capable of exporting/serializing to OSCAL's XML SSP format. When attempting to process this with [Saxon HE 10.2 one of the most common opensource XML/XSLT processing engines](http://saxon.sourceforge.net/), there is a core failure because XML does not support any whitespace before the opening XML tag like so`     <?xml`, not `<?xml`.

**To Reproduce**
1. Go to an example project with a partially or complete system security plan.
2. Click on the System Security Plan towards the bottom.
3. Click on the OSCAL XML export link (`https://test.govready.com/tasks/{id}/system-security-plan/download/document/ssp_v1_oscal_xml/xml`)
4. Process download with a XML engine that is standards-compliant and see syntax exceptions during processing.

**Expected behavior**
A successful parse of the XML for my processing pipeline with out a runtime syntax parsing error.

**Error**
```xml
Error on line 1 column 8 of ssp_v1_oscal_xml.xml:
  SXXP0003  Error reported by XML parser: The processing instruction target matching
  "[xX][mM][lL]" is not allowed.
org.xml.sax.SAXParseException; systemId: file:/Users/Username/Downloads/ssp_v1_oscal_xml.xml; lineNumber: 1; columnNumber: 8; The processing instruction target matching "[xX][mM][lL]" is not allowed.
```

**Desktop (please complete the following information):**
 - OS: MacOS 10.15.6
 - Browser: Google Chrome Chrome
 - Version 87.0.4280.88 (Official Build) (x86_64)
 - Virtual Machine? No
 - Screen size 15.4-inch (2880 x 1800)

## Developer hints

Removing leading whitespace fixed the issue; will look at XML export code later this week to determine how/why this is occurring and attempt to PR back a fix if I can figure it out.

I determined this through research that led to [Atlassian documents](https://confluence.atlassian.com/jirakb/xml-restore-fails-with-message-the-processing-instruction-target-matching-xx-mm-ll-is-not-allowed-417367650.html), as I had never seen this type of error before.

## Acceptance criteria 

  GIVEN this issue ...
  WHEN I do this ...
  THEN this happens ...

**Additional context**

**Comment by gregelin** [comment]
@ohsh6o Thanks for identifying this issue. The SSP XML generation is needs re-working in several ways.

**Comment by tohch4** [comment]
@gregelin so I have started to review the CUB repository and having looked at this code base, I am have trouble telling where the OSCAL XML output occurs in either GovReadyQ or CUB, and we first looked at this in December. Is it in fact generated [by the `oscalize.py` file](https://github.com/GovReady/CUB/blob/main/oscalize.py)? I would love to help contribute back fixes if I can lend a hand. Thanks!

**Comment by gregelin** [comment]
@tohch4 We are not yet producing OSCAL in XML. We are only producing OSCAL in JSON in both GovReady-Q and CUB.
We'd love help integrating the NIST translation tools so we can also generate OSCAL in XML!

**Comment by gregelin** [comment]
I also noted a bug and created an issue. https://github.com/GovReady/CUB/issues/3

Trying to get Tom Wood's assistance.

Greg Elin
CEO, GovReady PBC
p: 917-304-3488
e: gregelin@govready.com

Sent via Superhuman ( https://sprh.mn/?vip=gregelin@govready.com )

**Comment by tohch4** [comment]
Cool, I will follow that issue and would love to pitch in however I can.

**Comment by gregelin** [comment]
@tohch4 The problem I encountered was related to now installing an NLP library. The `README` is now updated an bit clearer at the top of the page of how to install get started. Give it a try?

**Comment by tohch4** [comment]
I will definitely take a look. But I am a little confused: I saw no mention of lxml or a similar xml library in CUB or GovReadyQ, but I am certain you once showed me in a demo XML. Did you use one of the converters from OSCAL upstream to generate that or am I completely lost? I cannot tell where that came from, either in this repo or CUB.

**Comment by gregelin** [comment]
AJ,

Early implementation of OSCAL in JSON and XML was from text templates and not the serialization of a data object.

So we demo’ed XML OSCAL at one time. But now we are doing JSON version as a proper serialization of a data object. Next need to do the same for XML. That is why you can’t find lxml or other.

Greg Elin
CEO, GovReady PBC
p: 917-304-3488
e: gregelin@govready.com

Sent via Superhuman iOS ( https://sprh.mn/?vip=gregelin@govready.com )

**Comment by tohch4** [comment]
Fantastic, now I understand what I was missing. 🤦 I now am up to speed. Let me look at your approaches and I see where I can pitch in! :-)

**Comment by gregelin** [comment]
@tohch4 Some more background:

Questionnaires, also known as "compliance apps" in GovReady all have the ability to generate output documents that use the answers from the questions. We are partially utilizing an output document to generate the OSCAL JSON SSP.

Docs on compliance apps:
https://govready-q.readthedocs.io/en/latest/authoring-guide/understanding-compliance-apps.html

Here's an important closed PR that explains some of the plumbing of the code for the OSCAL JSON SSP:
https://github.com/GovReady/govready-q/pull/1286

The "lightweight ato" compliance app template that is leveraged:
https://github.com/GovReady/govready-q/blob/master/q-files/vendors/govready/govready-q-files-startpack/q-files/lightweight-ato/templates/ssp_v1_oscal_json.md

The generation of the SSP is currently pretty interwoven with the `guided-modules` Django app feature for generating output documents in general.

**Comment by tohch4** [comment]
As always, @gregelin, excellent context, thank you! I will dive in and connect some of the dots and fill in the voids in my understanding.
