### ISSUE TITLE
Environment value for multiple ALLOWED_HOSTS

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#1210]
**Describe the issue as a Story**
As an admin of Govready, I want to be able to set multiple `ALLOWED_HOSTS` via environment parameters in the `local/environment.json` file, so I can set enable "localhost" and ip addresses to make installation debugging easier.

**Expected behavior**
I want Django to accept multiple URLS in addition to domain indicated in the `govready-url` environment parameter by simply adding to the `local/environment_json`:
```
"allowed_hosts": ["localhost", "10.0.0.10"],
```

## Developer hints

The file `siteapp/settings.py` defines the `ALLOWED_HOSTS` parameter around line 73. We want to append in additional parameters. Something like:

```
# Append additional hosts to ALLOWED_HOSTS
if "host" in environment:
  for ah in environment["allowed_hosts"]:
    ALLOWED_HOSTS.append(ah)
```

## Acceptance criteria 

  GIVEN "allowed_hosts": ["localhost", "10.0.0.10"], is in `local/environment.json` ...
  WHEN I navigate my browser to http://10.0.0.10 ...
  THEN GovReady-Q pages appear ...

   Documentation is also updated, or at least a request is made to update.

**Comment by davidpofo** [comment]
This looks to have been handled in release [v0.9.3.2](https://github.com/GovReady/govready-q/compare/v0.9.3.2...v0.9.3.3)
