### ISSUE TITLE
Occasional Server 500 error when  long imports of multiple components in OSCAL

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#1245]
**Describe the bug as a Story**
GovReady displays "Server 500" error occasionally during long imports of multiple components in OSCAL. Checking the log reveals Python `critical work timeout` occurs.

**To Reproduce**
1. Go to component library
2. Import multiple OSCAL files, with each OSCAL file containing 12 or 20 components
3. Count spins, server may fail around 25 or more spinner rotations (an approximation of time)
4. Server will display "Server Error 500 Internal server error"

**Expected behavior**
GovReady imports all controls, or gracefully errors out because import taking too long.

Error seems correctable by just re-importing the file.

**Screenshots**

<img width="1017" alt="Screen Shot 2020-12-31 at 9 56 09 AM" src="https://user-images.githubusercontent.com/24979/103417601-e9635480-4b50-11eb-8cc2-9a5d35e1f118.png">

**Desktop (please complete the following information):**
 - OS: MacOS 14
 - Browser Safari

## Developer hints

See: https://stackoverflow.com/questions/47217880/critical-worker-timeout-error-on-gunicorn-django

## Acceptance criteria 

  Server does not crash on uploading large OSCAL files (at least files that do not take longer than 4 minutes to import)

**Comment by omarabed15** [comment]
@gregelin Can you provide a sample OSCAL file where this occurs? I don't have one with enough components to catch the issue. And when it says, for step 2 under the Reproduce steps:
> Import multiple OSCAL files, with each OSCAL file containing 12 or 20 components
are you trying to import multiple files at once, or one file at a time? The UI currently doesn't support uploading multiple files at once.
