### ISSUE TITLE
Improve success/error message on failed project move between portfolios

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#1253]
**Describe the issue as a Story**
As a user of Govready, I want an informative success and error messages in the browser when trying to move a project between portfolios, so I know the move succeeded and I can get help with the problem if the move failed.

The current error message just says that something went wrong. It is the standard error message for a failure that occurs in an AJAX save to the server.

**Expected behavior**
- [ ] Better message when project successfully moved between projects
- [ ] The error message provides understandable information about the problem preventing a project to move between portfolios (such as user does not have permission on destination portfolio).
- [ ] UI test created for error message

## Acceptance criteria 

- [ ] The error message provides understandable information about the problem preventing a project to move between portfolios (such as user does not have permission on destination portfolio).
- [ ] UI test created for error message

**Additional context**
Further improvements to #1203.

**Comment by davidpofo** [comment]
knocked this out in [PR ](https://github.com/GovReady/govready-q/pull/1535)
