### ISSUE TITLE
Users' email address is not added to profile on user creation with single-sign-on

### ISSUE THREAD

**Issue by nkerling10** [GovReady/govready-q#1260]
**Describe the issue as a Story**
As a user of Govready, I would like the users' email address to be automatically added to their user profile upon their creation as a user. Currently, no email address is added to their profile. This issue happens when utilizing Single Sign On.

**To Reproduce**
1. Invite a user to the platform
2. User accepts the invitation and their user account is created
3. Go to the admin panel and to the users menu
4. See that their username is set but not their email address

**Expected behavior**
Their email address should be set as well as their username. It's tedious to search and make contact with an individual based only upon their username, especially when there are multiple people with the same name.

**Screenshots**
N/A

## Developer hints

I imagine it would be in the same code location that adds a users' username to their profile. Not sure which file that is based on at the moment.

## Acceptance criteria 
Same as expected behavior.

**Comment by gregelin** [comment]
@nkerling10 We are working to fix this. We are in the process of changing the User account settings. See #633. Sorry for the awful delay on your request.

**Comment by gregelin** [comment]
@nkerling10 Can you say more about your SSO scenario?

I've been looking at this issue and wanted to provide some background, starting with self-registering and explaining how that effected Single Sign On, too.

In the original configuration of inviting people to a project, we thought a new user might receive an invite at EMAL_1 but want to register their new account using EMAIL_2. For that reason, the code does consider the invite email as a default in registering a new account.

Similarly, in the Single Sign On (SSO) use case, the SSO information sent to GovReady may (or may not) have email information, and it may be named differently. 

I'm continuing to look at the issue to see what we can do.
