### ISSUE TITLE
Project Requirements don't install correctly

### ISSUE THREAD

**Issue by omarabed15** [GovReady/govready-q#1275]
**Describe the bug as a Story**
As a developer of GovReady, I want to install the development libraries and dependencies of the system with a single requirements repository, and not manually.

**To Reproduce**
1. Clone the repository
2. Run `./install-govready-q.sh` or `pip3 install -r requirements.txt`
3. See error where gevent, greenlet, pyinstrument-cext, and/or pyinstrument fail to install

**Expected behavior**
Running `./install-govready-q.sh` should download the dependencies and start the local server running on a port.
Running `pip3 install -r requirements.txt` should download the dependencies and install them to a local folder.

**Screenshots**
Upon running `pip3 install -r requirements.txt`:
![image](https://user-images.githubusercontent.com/35661883/104093364-31246300-5258-11eb-8aa0-e3ebad94032c.png)

Upon running `pip3 install -r requirements.txt` (after commenting out gevent and greenlet):
![image](https://user-images.githubusercontent.com/35661883/104093353-1a7e0c00-5258-11eb-8220-a7d2e2766e31.png)

**Desktop (please complete the following information):**
 - OS: Mac OS Catalina (10.15.7)

## Developer hints
Resolve dependency issues.
Consider removing gevent and greenlet if not needed, or resolve the version issues.
Installing pyinstrument outside of the requirements.txt file worked, when running: `pip3 install pyinstrument==3.2.0`, so it's likely an issue with the hashes, and not with the actual dependency.

## Acceptance criteria 

Running `./install-govready-q.sh` downloads the dependencies and starts the local server running on a port.
Running `pip3 install -r requirements.txt` downloads the dependencies and installs them to a local folder, without the need to install any dependencies manually.

**Comment by bama4** [comment]
This is not an issue when running `pip3 install -r requirements.txt` on:
```
System Version: macOS 11.1 (20C69)
Kernel Version: Darwin 20.2.0
```

**Comment by davidpofo** [comment]
Fixed in last release
