### ISSUE TITLE
Should newly invited user have to go through profile module?

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#14]
When a user is invited to a question or invited to edit a module, should the new user have to fill out user profile module before being brought to the question and/or module?

Or should the user answer question and then on next login be sent to the profile module?

**Comment by JoshData** [comment]
We decided to take away the prompts to complete the profile in 8f9b06a6e51e5017181108c5a84770024c852654 and cbcc62af6c4e81c5590e6ab9859ac5324073c864.
