### ISSUE TITLE
Add Snyk IO Vulnerability Scanning to CircleCi Build

### ISSUE THREAD

**Issue by bama4** [GovReady/govready-q#1420]
**Describe the issue as a Story**
As a developer of GovReady, I wish to run Snyk.io on each push to determine any potential vulnerabilities.
I also wish to have reports of vulnerabilities in dependencies.

**To Reproduce**
N/A

**Expected behavior**
At each pull request/push, the CircleCi build for Snyk.io is executed to report vulnerabilities with the `requirements.txt` file.
I can also see reports in the Snyk Organization Account.

**Screenshots**
N/A

**Desktop (please complete the following information):**
N/A
 - Virtual Machine?
 - Screen size

## Developer hints
N/A

## Acceptance criteria 

  GIVEN a vulnerability in the dependencies of the repository
  WHEN I push up code/create a pull request
  THEN snyk io should create pull requests to address the vulnerabilities

- [x] GovReady Account needs to be set up for Snyk with API token changed to GovReady Account Snyk API token.
- [x] GovReady Project in Snyk needs to be specified as the project in the CircleCi Build `snyk-scan` parameters.
- [ ] Check if it is possible to have Snyk GovReady account create pull requests.

**Additional context**
CircleCi Instructions: https://circleci.com/developer/orbs/orb/snyk/snyk

**Comment by gregelin** [comment]
Completed.
