### ISSUE TITLE
importlib-metadata==3.4.0 because these package versions have conflicting dependencies

### ISSUE THREAD

**Issue by haribole** [GovReady/govready-q#1424]
python requirements have dependency issues.

**To Reproduce**
pip3 install -r requirements.txt

**Expected behavior**
Expected behavior is that all requirements are installed correctly

**Screenshots**

INFO: pip is looking at multiple versions of asgiref to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of appdirs to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of alabaster to determine which version is compatible with other requirements. This could take a while.
ERROR: Cannot install -r requirements.txt (line 172) and importlib-metadata==3.4.0 because these package versions have conflicting dependencies.

The conflict is caused by:
    The user requested importlib-metadata==3.4.0
    django-bootstrap3 14.2.0 depends on importlib-metadata<2.0.0 and >=1.5.0; python_version < "3.8"

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/user_guide/#fixing-conflicting-dependencies
root@gq1:/opt/govready-q# 
root@gq1:/opt/govready-q# 
root@gq1:/opt/govready-q# 
root@gq1:/opt/govready-q# 

**Desktop (please complete the following information):**
 - OS: ubuntu 18.04
 - Virtual Machine:  Docker

**Comment by gregelin** [comment]
@Dav1dV @davidpofo  - have we fixed this conflict with our most recent code?

**Comment by gregelin** [comment]
@haribole We are in the process of doing a new release that depends on Python 3.8 where we seem to be able to resolve all our dependencies (branch: develop). We are also working on a new docker version (see: https://github.com/GovReady/govready-docker).

Would you be able to run on Python 3.8?

**Comment by haribole** [comment]
Thanks so much! Yes, I can try with 3.8

**Comment by gregelin** [comment]
We hope to have the release out in next few days, @haribole!

**Comment by gregelin** [comment]
@haribole v0.9.2 is now available! v0.9.2 should have all the libraries worked out for Python 3.8 and 3.9.

Also, if you are feeling daring, we also have in a branch in development containing a new and improved `installer.py` script that replaces the existing `install-govready-q.sh` script. The branch is `pk-install-govready-q-py-20210226`.  If you want to try on Linux:

```bash
# clone repo
git clone https://github.com/GovReady/govready-q.git govready-q
cd govready-q

# checkout branch with new installer
git checkout pk-install-govready-q-py-20210226
# Set up python 3 virtual environment
python3 -m venv venv
source venv/bin/activate

# run installer and follow prompts
python install.py
```

**Comment by gregelin** [comment]
@haribole We have a new release v0.9.2.1 that should also work with Python 3.6. We fixed some library dependencies.

**Comment by gregelin** [comment]
Fixed.
