### ISSUE TITLE
Support Customer Specific word .docx template stored in the database

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#1437]
**Describe the issue as a Story**
As a user of Govready, I want to be able to use a different word document layouts for outputting the SSP, so that I can customize the headers, footers, and other details of the SSP to conform with my agency requirements.

**Expected behavior**
- User or admin can upload a .docx file to GovReady
- The uploaded .docx file is stored in the database
- User or admin can set the uploaded .docx file to be used as the `--reference-doc` by pandoc for generating the Word version of the SSP.
- More than one .docx file can be uploaded to be used ad the `--reference-doc`
- Eventually, user can immediately choose among different docx files and set a default
- Eventually, default document preferences can be set at the project level, the organization level, and the instance of GovReady level

### code

`guidedmodules.models.Task.download_output_document` around L1295 sets the `template` to be used as the reference document by `pandoc`. This is currently hard coded and needs to be set to different values.

```python
            # TODO: Currently this works with only one reference file;
            # /assets/custom-reference.docx. We should be able to point to a
            # reference file in a Compliance App.
            template = "assets/custom-reference.docx"

            # odt and some other formats cannot pipe to stdout, so we always
            # generate a temporary file.
            import tempfile, os.path, subprocess # nosec
            with tempfile.TemporaryDirectory() as tempdir:
                # convert from HTML to something else, writing to a temporary file
                outfn = os.path.join(tempdir, filename)
                # Append '# nosec' to line below to tell Bandit to ignore the low risk problem
                # with not specifying the entire path to pandoc.
                with subprocess.Popen(# nosec
                    ["pandoc", "-f", "html", "--toc", "--toc-depth=4", "-s", "--reference-doc", template, "-t", pandoc_format, "-o", outfn],
                    stdin=subprocess.PIPE
                    ) as proc:
                    proc.communicate(
                        doc["html"].encode("utf8"),
                        timeout=30)
 ```

### Considerations
- The term "template" or  "SSP Word Format" in this context generally means a Word `.docx` file that is used as reference format by `pandoc` to convert content to MS Word; "template" does not refer to a Ms Word `.dotx` _template_.
- An organizing installing GovReady might want to set a different default SSP template for all projects to use. Would the simplest implementation of be to leverage the `branding` directory by adding an `asset/custom-reference.docx` file? Would that already be automatically picked up by GovReady?
- A particular project may need a different "SSP Word Format" because of the target audience (e.g., producing a FedRAMP version an SSP).
- What if the install of GovReady is multi-tenant or pseudo-multi-tenant? How could different SSP Word Formats be stored and referenced as defaults for different organizations? 
- Current code block has `template = "assets/custom-reference.docx"` and it might be better to change name of `template` variable to `reference_doc` to be the same as the `pandoc` terminology.
- In addition to the SSP document, should/can the "template" be used by default by all the documents? What if there is one styling for the SSP document and a different styling for the PTA document?
- There is a UI issue of how the user would (a) select among different SSP Word Format and (b) upload an SSP.
- What if a user uploads an SSP that is structured incorrectly? (Leave that for future story/issue.)
- The Word reference doc primarily deals with headers, footers, text styles, etc, and does not address structural layout of the content. Currently, the layout of the content can only be changed within the Compliance App containing the output document definition. GovReady already supports multiple output document definitions associated with a compliance app (or compliance module).
- Can different/multiple reference documents be included in the `assets` directory of the compliance app? How would the `load_modules.py` handle those assets? How would the UI?
 
### Rules for the default reference document
Pseudo code:

```python
# The install of GovReady comes with a default custom reference file in `assets/custom-reference.docx`
ref_doc = "assets/custom-reference.docx"
# Is there an instance override?
if REFERENCE_DOC_INSTALL exists:
  ref_doc = REFERENCE_DOC_INSTALL
# Is there an organization default override?
if REFERENCE_DOC_ORG exists:
  ref_doc = REFERENCE_DOC_ORG
# Is there an project default override?
if REFERENCE_DOC_PROJECT exists:
  ref_doc = REFERENCE_DOC_PROJECT
```

### Where to store and manage alternative MS Word Template documents
Since we have tried to write GovReady to not have to use the file system (and thus be able to run on read-only file system for added security), additional reference docs must be stored in the database.

The `guidedmodules.models.TaskAsset` model provides an example of how the GovReady-Q database is already managing the storage of binary assets in the database.

Recommendation is that create a model called `guidedmodules.models.Asset` that would store arbitrary assets including additional optional reference doc MS Word docx files.  (We would not want to use exist `TaskAsset` model because that is closely tied with the questionnaires.)  

Proposed structure of `Asset` model:

```python
class Asset(models.Model):
    title = models.CharField(max_length=255, help_text="The title of this asset.", unique=True)
    asset_type = models.CharField(max_length=150, help_text="Asset type.", unique=False, blank=True, null=True)
    content_hash = models.CharField(max_length=64, help_text="A hash of the asset binary content, as provided by the source.")
    file = models.FileField(upload_to='guidedmodules/module-assets', help_text="The attached file.")
    created = models.DateTimeField(auto_now_add=True, db_index=True)
    updated = models.DateTimeField(auto_now=True, db_index=True)
    extra = JSONField(blank=True, help_text="Additional information stored with this object.")
    uuid = models.UUIDField(default=uuid.uuid4, editable=False, help_text="A UUID (a unique identifier) for this Asset.")
```

The recommendation to associate the reference document to a given project is adding a `settings` or `state` JSONField to `siteapp.models.Project` model whose schema supports a variety of parameters about the state/settings/defaults of the project. The extensible JSONfield will be used to a support a variety of customization and performance issue. But for now this JSONfield will be used to identify (a) the current default reference document for pandoc to use and (b) additional optional reference documents for pandoc.

## Acceptance criteria 

GIVEN I am on the task finished page,
WHEN I am on the task finished page for an SSP in Lightweight ATO,
THEN I can clearly see the name of the default Word document that will be used as the reference document to generate the MS Word output version and maybe I can even download that reference document to review, edit and eventually upload an alternative version as an additional document reference choice.

GIVEN I am an admin,
WHEN I am in Django's admin interface,
THEN I can navigate to the guidedmodules Asset model and upload an additional Word docx file to be used by pandoc as a custom reference document.

GIVEN I am an admin,
WHEN I am in Django's admin interface,
THEN I can navigate to the siteapp Project model and adjust the default value of the Word docx file to be used by pandoc as a custom reference document in the Project.state JSONField.

GIVEN an alternative reference document has been uploaded to the Asset table and defined as the default reference document to be used by pandoc to output an SSP,
WHEN I output the SSP of the project,
THEN I get an SSP using the custom reference template.

**Comment by alexanderward** [comment]
[WARNING] Could not fetch resource '/tasks/4/system-security-plan/media/app.png': PandocIOError "/tasks/4/system-security-plan/media/app.png" /tasks/4/system-security-plan/media/app.png: openBinaryFile: does not exist (No such file or directory). When producing docx
