### ISSUE TITLE
Creating an implementation statements associated with Control PE-11(1) causes crash in component library

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#1442]
**Describe the bug as a Story**
When authoring an implementation statement associated with Control PE-11(1) for a component in the library, an error occurs when trying to save the control.

Put another way authoring controls for PE-11(1) fails. This failure occurs in the component library.

**To Reproduce**
1. Go to component library and pick a component.
2. Click on 'Component Implementation Statements' tab.
3. Click on 'Add component statement' button and open the component to author/edit the control
4. Type "PE-11" in Control: Select a control select box and wait for options to populate.
5. Choose "PE-11 (1) ..."
6. Author a control.
7. Hit Save
8. Reload page and get error:

<img width="1724" alt="Screen Shot 2021-02-27 at 2 06 00 PM" src="https://user-images.githubusercontent.com/24979/109398863-fc05ca00-7904-11eb-8e40-0daa35e2a51c.png">

The reason the component no longer displays is because the data is incorrect in the statement that was created from authoring the control associated with PE-11 (1).

The reason the statement associated with control PE-11 (1) has incorrect data is because a line within the code that save the statement parses the string in the control select field to determine the the catalog key and a dash is being used to determine parse/split the string. Because PE-11 (1) contains a dash in the name of the control, there are two dashes are causing a parsing error with the current code.

Checking the statement in the database shows that instead of control catalog key in the `sid_class` field we have part of the name of the control itself from the incorrect parsing.

<img width="1311" alt="simplesense_monitoring" src="https://user-images.githubusercontent.com/24979/109399128-8995e980-7906-11eb-92ae-f82b72971693.png">

**Expected behavior**
Control is correctly authored and save.

**Screenshots**

**Desktop (please complete the following information):**
Error duplicated on Mac and Windows platforms

## Developer hints

The problem is certain controls have the same id whether the control comes from 800-53_rev4 or 800-53_rev5, so we need to display the catalog as part of the select box. Alternatively we could have one drop down for catalog and one for conrols, but I think that is painful. Another solution might be to populate an hidden field with the correct catalog key in order to pass that value cleanly to the save routine --- but you'd still need to get that control catalog key probably parsing what is in the control name. 

So the essential problem is a better representation of the control id + control name + control catalog so that all is readable to the user AND friendly for parsing the results passed. It might be that because we pass the KEY of the selected choice and not the display value, we can use a better key which avoids the parsing error.

Look at this file, template, etc

## Acceptance criteria 

  GIVEN when I author an implementation statement associated with PE-11 (1)
  WHEN I do go to look at the component and its control implementation statements in the component library ...
  THEN no error is encountered.

**Additional context**

**Comment by davidpofo** [comment]
@gregelin turns out it was how a piece of javascript was splitting the display text in the element details tab template. #1451
