### ISSUE TITLE
`fetch-vendor-resources.sh` fails on macOS

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#1443]
**Describe the bug as a Story**
`fetch-vendor-resources.sh` fails on stock macOS. This is because `fetch-vendor-resources.sh` downloads and runs [neverpanic/google-font-download](https://github.com/neverpanic/google-font-download) which depends on, and checks for, Bash 4+.  On stock macOS, bash will never be higher than 3.2, due to Apple's decision about GPL licensing.

(A workaround is for the user to install Bash 4+ with, for example, Homebrew. But this complexifies system requirements and setup for the user.)

**To Reproduce**
1. On macOS that doesn't have a non-stock bash, run `fetch-vendor-resources.sh` (or one of the other scripts that runs `fetch-vendor-resources.sh`).
2. After a number of lines of output, observe this line and the related progess hash characters:
```
https://raw.githubusercontent.com/neverpanic/google-font-download/d7bb34e0c5fa01d9411213fd1a1363317d3ceb11/google-font-download...
```
3. Observe this error: "Error: This script needs Bash 4.x to run." (It is output by the google-font-download script.)

**Expected behavior**
* On stock macOS, `fetch-vendor-resources.sh` runs to completion without error.
* After `fetch-vendor-resources.sh` runs, there are Google Font files in `siteapp/static/vendor` (Hind_* and Lato_*)

**Desktop (please complete the following information):**
 - OS: macOS 11.2.1 Big Sur (Intel)
 - Browser: Chrome "Version 88.0.4324.192 (Official Build) (x86_64)"
 - Version: `develop` branch, 678b98c3039d8d4a5f8ca7373e1cb0abf239928f
 - Virtual Machine: no
 - Shell: zsh

## Developer hints

Will fix with `pk-better-google-font-download-20210227` branch.

## Acceptance criteria 

GIVEN stock macOS,
WHEN I run `fetch-vendor-resources.sh`
THEN it runs to completion without error,
AND THEN there are Google Font files in `siteapp/static/vendor` (Hind_* and Lato_*).

**Comment by gregelin** [comment]
@peterkaminski Thanks for the fix to avoid bash4 on Mac. I'm also wondering about simply not using the Google fonts?
