### ISSUE TITLE
Is controls.models.ElementControl.get_controls_by_element needed

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#1446]
Is the method `controls.models.ElementControl.get_controls_by_element` being used anywhere in the code? Is it needed?

I was adding `natsorted` to the controls associated with a `system.root_element` when I noticed `controls.models.ElementControl.get_controls_by_element` and was uncertain how method was being used or if being used.

**Comment by davidpofo** [comment]
@gregelin No it is not used anywhere. A deeper question is the whole model of ElementControl needed? I don't see its use anywhere besides Admin to display it. An issue with what I think this model is that it has one oscal catalog key (sid class) as a field which will make it even more conflicting when we are accomodating multi-catalog projects.

**Comment by gregelin** [comment]
@davidpofo ElementControl currently plays a critical role as the linking table to associate selected controls with the `system.root_element`.

**Comment by gregelin** [comment]
@davidpofo We can delete `controls.models.ElementControl.get_controls_by_element` -- or maybe comment out for a couple of releases -- since that method is not being used. But I'm pretty sure deleting `controls.models.ElementControl` would break many things.

**Comment by davidpofo** [comment]
> @davidpofo We can delete `controls.models.ElementControl.get_controls_by_element` -- or maybe comment out for a couple of releases -- since that method is not being used. But I'm pretty sure deleting `controls.models.ElementControl` would break many things.
 @gregelin 
yes, you are right I see that is a one-liner in the models under assign_baseline_controls. Might be able to phase this out but for now I see no reason to. The get_controls_by_element should be commented out at least if not deleted.

**Comment by gregelin** [comment]
Will be closed by #1448.
