### ISSUE TITLE
Create Tag Mechanism - Elements

### ISSUE THREAD

**Issue by alexanderward** [GovReady/govready-q#1450]
On the Component Library page:
- User should be able to view new column for tags
- User should be able to edit the component's tag via the edit page
- User should be able to create a new component w/ tags 
* Get more info on how this is done via the Project page

Proposed:
- Page will use ajax calls to handle the CRUD of these tags.
- Typeahead will use  /tags/ or /tags/?search=yoursearchere  (This will only search beginning of string of label)
- If a tag doesn't exist, the user should be able to create a new tag via the urls:
  * /tags/_save w/ body of {"label": "sampletagname"}
  * /tags/<tag_id>/_delete  (This will delete tag for part of the app if used by another piece)
- To add an existing tag to a Element use the following endpoints:
  * /controls/elements/<element_id>/tags/<tag_id>/_add 
  * /controls/elements/<element_id>/tags/<tag_id>/_remove
  * /controls/elements/<element_id>/tags/ (will give you a list of tags for that element)

If you want to access the tags for a template use the query of Element.objects.prefetch_related('tags').get(id=<element_id>).tags.all()

Tags can be added to any model by:
- adding the TagModelMixin to your django model.  
- adding urls via the helper function build_tag_urls:
- Example: *build_tag_urls(r"^elements/(\d+)/", model=Element),  # Tag Urls

Branch: tags-feature

**Comment by gregelin** [comment]
I've done some work on this ticket, adding the display of tags to component pages. Displaying tags underneath the description column rather than in a new column.

**Comment by gregelin** [comment]
This work has been completed. #1475
