### ISSUE TITLE
Hacks in the module architecture

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#147]
Things to revisit:
- We don't have a "only show this question if ___" field for questions. So instead I'm using impute conditions to _hide_ a question when a condition is met. But that's the opposite of the natural way some conditions work.
- We don't have a way to multiplex questions. For example, there may be three ways to ask a question and we want to choose the way that is appropriate for the user based on their previous answers. But the result should end up in the same template context variable. The way I do this now is by creating multiple questions; each question has a similar impute condition that controls which displays; and there's a final question which does the multiplexing by using an impute condition that repeats all of the impute logic again to choose which question to pull the answer from.

**Comment by gregelin** [comment]
won't fix
