### ISSUE TITLE
Deploying with Docker link on DockerHub page is broken

### ISSUE THREAD

**Issue by wesley-dean-flexion** [GovReady/govready-q#1660]
The link on the [govready/govready-q page](https://hub.docker.com/r/govready/govready-q) on DockerHub to '[Deploying with Docker`](https://govready-q.readthedocs.io/en/latest/installation-and-setup/container-based-installation/index.html)' is broken (i.e., following the link results in a 404 page not found error).

**Comment by davidpofo** [comment]
@wesley-dean-flexion Production deployment instructions can be found [here](https://govready-q.readthedocs.io/en/latest/installation/production/index.html?highlight=deploy%20docker) and local development deployment [here](https://govready-q.readthedocs.io/en/latest/installation/development/index.html).

**Comment by wesley-dean-flexion** [comment]
Understood.  The issue isn't that I couldn't find the documentation, it's that the link is broken.

**Comment by davidpofo** [comment]
@wesley-dean-flexion We are taking down this docker hub page as we are working in stacks now. For now we just support docker compose https://github.com/GovReady/govready-deployments.
