### ISSUE TITLE
Server Error 500 when importing FedRAMP Rev4 Moderate Baseline (oscal version 1.0.0) Catalog

### ISSUE THREAD

**Issue by gponto** [GovReady/govready-q#1665]
**Describe the bug as a Story**
After importing https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/baselines/rev4/json/FedRAMP_rev4_MODERATE-baseline-resolved-profile_catalog.json into `~/govready-q/local/controls/data/catalogs/test_catalog.json` accessing the "Controls" menu returns a `Server Error (500)`

**To Reproduce**
1. Copy https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/baselines/rev4/json/FedRAMP_rev4_MODERATE-baseline-resolved-profile_catalog.json into `~/govready-q/local/controls/data/catalogs/test_catalog.json`
2. Copy the very simple `test_baselines.json` (code below) that references the controls in Catalog into `~/govready-q/local/controls/data/baselines/test_baselines.json`
```JSON
{
    "low" : {
        "controls":
            ["ac-1"]
        },
    "moderate" : {
        "controls":
            ["ac-1", "ac-2"]
        },
    "high" : {
        "controls":
            ["ac-1", "ac-2", "ac-3"]
        }
}
```
2. Click on 'Controls'
![image](https://user-images.githubusercontent.com/31080393/127232468-75d25d89-108e-436e-b9ab-cf32ce1b3860.png)
3. **BUG:** A `Server Error (500)` is returned.
![image](https://user-images.githubusercontent.com/31080393/127233359-9122fef8-8f42-40aa-b012-99bcb6069d9a.png)

**Expected behavior**
When importing an OSCAL 1.0.0 catalog such as is provided by FedRAMP (https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/baselines/rev4/json/FedRAMP_rev4_MODERATE-baseline-resolved-profile_catalog.json), GovReady-Q should be able to display the controls from the catalog, and avail those controls for import into a Project such as Speedy SSP.

**Screenshots**
_See screenshots within **Steps to Reproduce** above._

**Desktop (please complete the following information):**
OS: Docker/Ubuntu 20.04 (https://github.com/GovReady/govready-deployments/tree/main/deployments/docker_compose)
Browser Chrome
Version: v0.9.6-dev
Virtual Machine?: Yes/Docker

## Developer hints

Look at this OSCAL 1.0.0 Catalog: https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/baselines/rev4/json/FedRAMP_rev4_MODERATE-baseline-resolved-profile_catalog.json.  I noticed all other test cases are based on OSCAL 1.0.0-milestone3 which might require parsing changes to handle.

## Acceptance criteria 

```cucumber
GIVEN I import a OSCAL 1.0.0 Catalog and compatible Baseline into GovReady-Q such as https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/baselines/rev4/json/FedRAMP_rev4_MODERATE-baseline-resolved-profile_catalog.json
WHEN I click on "Controls"
THEN The imported catalog should appear.
```

## Additional Details
We can successfully import an OSCAL 1.0.0-Milestone3 Catalog (https://github.com/GovReady/govready-q/blob/main/fixtures/test_catalog.json) using the workflow described in this issue which is why we suspect the problem has to do with parsing the newer OSCAL 1.0.0 Catalog provided by FedRAMP.

**Comment by gponto** [comment]
For reference, see ongoing discussion with @davidpofo here: https://github.com/GovReady/govready-q/discussions/1663#discussioncomment-1135463

**Comment by gregelin** [comment]
@gponto This issue is turning to be related to several items. We're working our way through it.

In addition to upgrading to OSCAL 1.0.0 we've also been moving the control catalogs into the database for better performance.  

I'll take a closer look at this issue and see what the latest is and give you an update.

**Comment by gregelin** [comment]
@gponto I've confirmed the issue is that the catalog https://raw.githubusercontent.com/GSA/fedramp-automation/master/dist/content/baselines/rev4/json/FedRAMP_rev4_MODERATE-baseline-resolved-profile_catalog.json using OSCAL 1.0.0 format. We need to adjust our routines.

**Comment by gbrown-gis** [comment]
@gregelin  - Just curious what the status is for supporting OSCAL 1.0.0 format.  Thanks!
