### ISSUE TITLE
Error with pygithub in Docker

### ISSUE THREAD

**Issue by jasonotu** [GovReady/govready-q#1732]
Hi all,

I am trying to run the dev environment in Docker, but I am getting the following error when docker compose runs as it collects pygithub. I'm wondering if the hash needs to be updated within requirements.txt?

```
Collecting pyjwt>=2.0
ERROR: In --require-hashes mode, all requirements must have their versions pinned with ==. These do not:
pyjwt>=2.0 from https://files.pythonhosted.org/packages/2a/4d/67cc66a0c49003dc216fc73db2d05a3b80c7193167fd113da1f2c678ac2a/PyJWT-2.3.0-py3-none-any.whl#sha256=e0c4bb8d9f0af0c7f5b1ec4c5036309617d03d56932877f2f7a0beeb5318322f (from pygithub==1.55->-r requirements.txt (line 818))
```

```
cd dev_env
python run.py init
python run.py dev
```

**Desktop**
 - OS: MacOS
 - IDE: PyCharm, Conda, Python 3.8, Docker Desktop 4.1.1

**Comment by gregelin** [comment]
@jasonotu I'll test and publish a fix. In the meantime, try updating your libraries:

```bash
cd path/to/your/govready-q
# Create a branch
git checkout -b lib-fix
# Update libraries and get hashes for all libraries
./requirements_txt_updater.sh 
```

Once that is done, you can `cd dev_env` and run `python run.py dev` again. (It is only necessary to `init` once.

**Comment by jasonotu** [comment]
Thanks very much!
