### ISSUE TITLE
Avoiding errors on load_modules

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#176]
### Story

As a developer, I don't want to accidentally trash the database. I heard Greg once trashed his local database because of a recursive sym link in his `modules` directory. I'd like a way to check for possible errors before loading modules.
### More details

Possible errors:
- [ ] recursive sym links in `modules` directory
- [ ] too many modules to update (eg, does updating modules scale to many projects and modules?
- [ ] is there a way to roll back database?
- [ ] what if database of system crashes while modules are being loaded?

**Comment by JoshData** [comment]
I don't think this issue applies anymore now that apps are loaded from the UI and not from load_modules.
