### ISSUE TITLE
security issues identified by 20Kleague

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#208]
See https://task.kiwi/jeffreycarr/u2vS3AfVvcmG/penetration-test. Here's what's left:

High-ish Priority:
* Raise iteration count of current password hashing algorithm, or replace with bcrypt or strong.
* [mostly done] Enable security headers X-XSS-Protection, X-Content-Type-Options, Strict-Transport-Security, HTTP Public Key Pinning. Some of these are already implemented in non-debug deployments. Need to consider the rest. Also check that cookies are set as secure, set csrfcookie as HttpOnly; secure (these should already be working in production).

Medium priority:
* [done] Cross-domain script include, Cross-domain referrer leakage. We're loading Emojione via a CDN. Could be improved. I tried to fix this but it took too long because the Emojione distribution is 100MB and I didn't want to deal with that. (#209)

Low-priority:
* [done] Enforce a strong password policy.
* 2FA/MFA system (#195).
* Implement checks for correct types for variables.
* Check use of asserts to make sure they're not critical code paths.
* Login form autocomplete enabled. Probably fine.

**Comment by gregelin** [comment]
Closed due to age.
