### ISSUE TITLE
create modules to explain fail2ban and Let's Encrypt setup

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#214]
Create some modules that enable us to give users weekly repeatable security assignments where they learn to do a task, like setting up fail2ban or https, and they actually implement it on one of their systems.

The module can have some Python code to check if the system was correctly modified. e.g. It can make some SSH requests to a system and see if it gets banned; it can make an HTTPS request and see if it comes back with a valid certificate.

We will need to change the account settings project used by the Organization that these users log into to not collect information that would only be relevant to a user's role in an actual organization.

We will test the modules by sending them to a few friends.

**Comment by gregelin** [comment]
Moved to https://github.com/GovReady/govready-apps-dev/issues/11
