### ISSUE TITLE
inviting a user from the new project page doesn't set an invitation message

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#230]
As a result, the email and the invitation interstitial show an empty blockquote which happens to also mess up the HTML email.

**Comment by gregelin** [comment]
@JoshData Is "inviting a user from the new project page doesn't set an invitation message" still an issue?

**Comment by JoshData** [comment]
I don't recall looking into this, so it is probably still an issue.

**Comment by gregelin** [comment]
Closed due to age.
