### ISSUE TITLE
favicon

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#245]
Lauren points out we don't have a favicon on Q (shows as the icon when you bookmark pages, etc.).

**Comment by JoshData** [comment]
Doesn't appear that we do. Do we have a square logo?

**Comment by JoshData** [comment]
Nevermind, we have https://raw.githubusercontent.com/GovReady/govready-q/master/siteapp/static/img/brand/favicon.ico. Not sure why it didn't show up. Will look further.

**Comment by JoshData** [comment]
I had added the favicon to the org subdomain pages but not the general landing page. Fixing now.

**Comment by gregelin** [comment]
Will favicon fix be arriving in an upcoming pull request?
