### ISSUE TITLE
replace my instrumentation with Snowplow or something similar

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#248]
@laurenancona suggests Snowplow (https://github.com/snowplow/snowplow), an open source analytics event  backend, rather than our ad hoc database table. Snowplow seems to basically be a replacement for just the event data collection aspect of Google Analytics that we can run behind firewalls. There's no UI (but we made our own analytics UI so far anyway).

**Comment by gregelin** [comment]
Added to roadmap
