### ISSUE TITLE
Is it possible that Q does not like dashes ("-") in question IDs?

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#263]
I was having problems getting impute condition to work. What seemed to fix it was changing question id from `q-1` to `q1`. Is it possible that Q does not like dashes in question ids?

impute works
```
impute:
  - condition: q1 == 'no'
    value: ~
```

impute fails:
```
impute:
  - condition: q-1 == 'no'
    value: ~
```

**Comment by JoshData** [comment]
http://jinja.pocoo.org/docs/2.9/api/#notes-on-identifiers

I'll add a check for this in load_modules.
