### ISSUE TITLE
when a user is newly invited to help on a project, they can't see the apps that have been selected as answers to top-level project questions

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#280]
* I see the question w/o the selected app's icon and title
* when I click, I'm taken to choose an app, but then at the end there's an error that says an app has already been chosen
* also, I can't answer any questions in child-modules because they each have as their editor the user who started them

**Comment by gregelin** [comment]
@JoshData This seems like a potential blocker for ordinary use cases. Where do we stand with this issue of when a user is newly invited to help on a project, they can't see the apps that have been selected as answers to top-level project questions?

**Comment by JoshData** [comment]
Yeah we haven't made any progress on this one yet.

**Comment by gregelin** [comment]
I thought we wrapped up this issue (user is newly invited to help on a project, they can't see the apps that have been selected as answers to top-level project questions)?

**Comment by gregelin** [comment]
Kanban UI fixes this.
