### ISSUE TITLE
Question Title vs Question Prompt in editor (technical debt)

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#283]
Questions currently display question title if prompt is blank. Adding an prompt in editor results in displaying only prompt in rendered question and question title. Editing again to remove prompt so question title is displayed in rendered question fails because editor reports error that prompt is missing when saving edited question.

(Acknowledging this is only an issue given early state of authoring tool, but wanted to capture for later.)

**Comment by JoshData** [comment]
I think the prompt is supposed to be a required field / you shouldn't have a blank prompt to begin with.
