### ISSUE TITLE
Create a new organization on govready.com with an existing user accounter

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#290]
I just tried to create cwds.govready.com from the login at q.govready.com. I was unable to do that because my username 'gregelin' was already in use.

It should be possible for an individual with an existing GovReady account to also create a new organization account.

**Comment by JoshData** [comment]
Just log in first using the form on the right-hand column. :-P

**Comment by gregelin** [comment]
Just figured that out myself.

![never-mind-gilda-radner-rosanne-rosannadanna](https://user-images.githubusercontent.com/24979/30888682-c453ebda-a2d6-11e7-905c-7793f5a1d051.jpg)
