### ISSUE TITLE
Improve UI of compliance catalog

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#292]
Simplify presentation of compliance apps in the catalog. Remove square outlines. Shift icon to left side of app title.

**Comment by JoshData** [comment]
We made improvements:

![image](https://user-images.githubusercontent.com/445875/31358868-680e0d30-ad15-11e7-85ff-e8428f561f8a.png)

ff2b4e34884953bff80434e4c372653a966ac106 7a1ddcd0c48797d938bb88a27950e141a577eee5 0a193a75e9c884d9a5e586fe5b0ddeb1097c3226 9bf39bacff750d8a4033d7c4dbfcff72963b2f27 87722d0e5b1f4c19c2a4654911726cf1620f4805
