### ISSUE TITLE
Better error for missing App source path

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#294]
A local folder containing compliance apps can be deleted and a github repository containing compliance apps can be deleted (or renamed) independently of the `App source` record in Q's database.

Currently Q crashes from a missing or misconfigured App source with the following error.

```
ValueError at /store
There was an error opening <AppStore <class 'fs.osfs.OSFS'> ['/mnt/apps/generic']>: root path does not exists
```

Q should gracefully handle the error of a missing App source (or a misconfigured App source `Spec` field). At the very least, instead of crashing Q should report which App source is the problem and recommend the user fixes it. Even better, Q should report the error and allow visitor to choose to continue.

**Comment by JoshData** [comment]
Fixed in d76e3b767ae5c1a4fdd0dc400fff33ca41eea80e and 8f7b37c6781c911ab4e8644bbd8b5143217ee0b6.
