### ISSUE TITLE
Add documentation for the end-user.

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#295]
We have documentation explaining GovReady-Q from developer and administrator perspective, but we don't have documentation explaining how the end-user can use GovReady-Q. We aren't explaining selecting an app from a catalog, adding other apps, starting apps, inviting people, the templates, etc.

- [ ] logging in; different accounts for different organizations
- [ ] maintaining profile
- [ ] organization profile
- [ ] permissions model
- [ ] what is a compliance app from a user perspective
- [ ] selecting apps from the catalog
- [ ] adding apps to a top level app
- [ ] starting an app
- [ ] delegating to others
- [ ] inviting others
- [ ] starting a discussion
- [ ] responding to a discussion
- [ ] responding to a discussion in email
- [ ] inviting others
- [ ] templates
- [ ] editing apps
- [ ] editing app templates
- [ ] creating apps

**Comment by davidpofo** [comment]
All of these items are address in our [readthedocs user guide](https://govready-q.readthedocs.io/en/latest/user-guide/user-guide.html) and [Authoring guide](https://govready-q.readthedocs.io/en/latest/authoring-guide/compliance-app-authoring-tutorial.html)
