### ISSUE TITLE
Documentation and example app showing how an image/diagram gets incorporated into an SSP

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#300]
## Story
As a developer, I want to see documentation and a reference example of images are included in output documents (especially SSP).

## More info
Developers familiar with markdown are going to be tempted to include an image using `![](imagepath.jpg)` or `<img src="imagpath.png">`. The existence of the `assets` folder in each compliance app directory also suggests and image can be included from the `assets` directory. But since those don't work, we need to provide documentation of how to do it and explain why images are incorporated as answers to questions. Having a sample app adjusted to include a sample system diagram would be very helpful.

**Comment by JoshData** [comment]
Images _can_ be included from the assets folder using `![]` Markdown syntax... and maybe also img tags (but we should discourage that). Is it not working?

**Comment by gregelin** [comment]
What would be the syntax for including an image in the asset directory
within the top level compliance app?


Greg Elin
CEO, GovReady PBC
p: 917-304-3488
e: gregelin@govready.com

**Comment by JoshData** [comment]
If there's a file at `assets/file.png`, then `![](file.png)` should work.

**Comment by gregelin** [comment]
That sounds, too easy...

**Comment by gregelin** [comment]
Documentation exists here:

https://github.com/GovReady/govready-q/blob/master/Schema.md#module-assets
