### ISSUE TITLE
README.md refers to appsources.json, but there is no appsources.json

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#307]
In README.md, lines 53-54 are these:

`53    # A default AppSource for https://github.com/GovReady/govready-sample-apps.`
`54    python3 manage.py loaddata deployment/docker/appsources.json`

However, there is no `appsources.json` in `deployment/docker/`, or elsewhere in the project.

Running the command produces the following error:

`CommandError: No fixture named 'appsources' found.`

It seems that either the documentation should not refer to `appsources.json`, or a `deployment/docker/appsources.json` file should be included in the repo

**Comment by gregelin** [comment]
We need to change this reference to explain how to add sample apps.

**Comment by JoshData** [comment]
The text was moved in 60e3ac7c80b3408c6cbbe634f1ba809bc0d2e998 to docs/Install.md, then in 2e4f46e77adcf9c5862925db1a2cb3fc911fc8b1 to deployment/local/README.md, and then fixed in e15aaabcb1fb7b14e09eef8b9c2f1ac140691585.
