### ISSUE TITLE
pay for pyup.io?

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#308]
https://pyup.io/safety/ is a database of Python package vulnerabilities. I'm working on adding it to our CI pipeline. We should consider paying for an API key which gives non-delayed info, otherwise it gives one-month-delayed info.

**Comment by davidpofo** [comment]
@gregelin I am assuming that I can close this one.

**Comment by gregelin** [comment]
Yes.

Greg Elin
CEO, GovReady PBC
p: 917-304-3488
e: gregelin@govready.com

Sent via Superhuman ( https://sprh.mn/?vip=gregelin@govready.com )
