### ISSUE TITLE
libffi-dev required during install of cairocffi (from mondrianish)

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#310]
**Overview**

While installing govready-q on a minimal Ubuntu 16.04 LTS box, `pip3 install -r requirements.txt` stopped with an error due to a unfulfilled dependency.

**What I was doing**

* created a minimal Ubuntu 16.04 LTS box
* followed the top-level govready-q `README.md` instructions
* ran `pip3 install -r requirements.txt`
* execution stopped with the error `c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory`, see attached text file for complete stack trace: 
[libffi-dev-missing-error.txt](https://github.com/GovReady/govready-q/files/1451261/libffi-dev-missing-error.txt) (note that "Using cached cairocffi-0.8.0.tar.gz" message is because this error dump is taken from a second run of the install, which failed the same was as the first)

After doing a web search for possible fixes, I used apt-get to install `libffi-dev`.  Rerunning `pip3 install -r requirements.txt` then succeeded.

**Possible fixes**
* add `libffi-dev` to the list of suggested packages to install before running the command
* adjust `requirements.txt` to include a package which fulfills the dependency, or to exclude packages which depend on `libffi-dev`

**Comment by JoshData** [comment]
> add libffi-dev to the list of suggested packages to install before running the command

We should do this one.

(The libffi library is a dependency of the cryptogrphy library that we use to store encrypted user answers to questions.)

**Comment by peterkaminski** [comment]
Makes sense, I'll do that.

**Comment by JoshData** [comment]
Just adding a note that this issue originally came up because of mondrianish's dependency on libcffi, which I subsequently removed in mondrianish, but I think it remains a problem because of the cryptography library.

**Comment by gregelin** [comment]
Closed due to age.
