### ISSUE TITLE
binding runserver: localhost:8000 vs. 0.0.0.0:8000

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#313]
The "kick-the-tires" setup documented in /README.md uses the default Django runserver binding to `localhost:8000`.  This is fine if the tire-kicker is setting up govready-q on the box on which they are running; however, if they prefer to tire-kick (or test or whatever) on a VM, it doesn't work, since `localhost` (or equivalently, `127.0.0.1`) binds to the VM's internal eth interface, instead of the interface reachable from the host machine.  To make it work, you need to tell runserver to answer on any interface, i.e., `./manage.py runserver 0.0.0.0:8000`.

I ran into this problem when I was first trying out GovReady, and it proved a little difficult to diagnose.  The symptom is that after starting runserver, the app will respond to HTTP requests from inside the VM (where I was trying HTTP by hand; it was a barebones server box, and didn't have a GUI or web browser), but from my host machine, the port would answer but immediately hang up with no output.

Trying SimpleHTTPServer inside the VM worked for both internal connections and connections from the host, so I knew I had my port forwarding set up correctly, and that the problem was with Django's configuration.

You can see a similar sentiment and use case expressed in [Django Project ticket #27537](https://code.djangoproject.com/ticket/27537).  Sinatra (Ruby) anticipated this need, too, with a [:bind configuration directive](http://www.sinatrarb.com/configuration.html#bind---server-hostname-or-ip-address).

I suggest we consider changing our examples from `./manage.py runserver` to `./manage.py runserver 0.0.0.0:8000`.

On the pro side, things will work the same as they do now from the local machine, and things will be set up to work if the user has set up govready-q within a VM and is trying to hit it from the VM's host -- no debugging or head-scratching involved.  It may also segue more easily into running automated tests against govready-q from environments set up to use VMs for testing.

On the con side, `0.0.0.0` may be less recognizably "localhost" for some people, and of course, it's not the standard Django default (although that might evolve to change, given the changes made in connection with ticket #27537).

It's possible that there are minor security implications; if govready-q only listens to its internal eth interface, it's harder to crack open.  However, even if it listens on its external eth interface (via 0.0.0.0), that interface should still be protected by regular enterprise network security (i.e., it is still behind the corporate firewall).

If we prefer to leave the default, we may still want to document the issue, to make it easier for tire-kickers to try govready-q.

**Comment by medined** [comment]
I would like more information about this issue. I would like to run the server on an AWS EC2 instance. While I can connect to the running server using curl after I SSH into the server, I can't connect via a web browser. How can I tell the server to bind to 0.0.0.0 instead of localhost or 127.0.0.1?

**Comment by JoshData** [comment]
Hi @medined.

The answer may depend on how you're deploying GovReady-Q. If you're running the source code directly on the AWS instance and you're using `./manage.py runserver`, you can instead run:

    ./manage.py runserver 0.0.0.0:8000

If you're using our Docker deployment, you can use our `--bind` option described in https://govready-q.readthedocs.io/en/latest/deploy_docker.html.

Keep in mind that if you're using `./manage.py runserver`, that's meant for testing only --- it isn't meant to be used in production.

If you're running GovReady-Q another way, let me know and I can try to help further. Also, we'd be glad to talk over the phone and learn more about what you are looking to use GovReady-Q for.

**Comment by medined** [comment]
Thanks for the quick response. I've created a GitHub project at https://github.com/medined/provision-govready-using-cloudformation so that I can repeatedly build a server for testing. 

The important bit is the UserData section which I show below:

```
          yum update -y
          yum install -y docker
          service docker start
          usermod -a -G docker ec2-user
          PUBLIC_IP=$(curl --silent http://169.254.169.254/latest/meta-data/public-ipv4)
          wget --quiet https://raw.githubusercontent.com/GovReady/govready-q/master/deployment/docker/docker_container_run.sh
          chmod +x docker_container_run.sh
          sudo -H -u ec2-user bash -c './docker_container_run.sh --bind $PUBLIC_IP:8000'
```

Is that the --bind parameter that you mentioned? 

The response that I am getting is "Bad Request (400)". The docker container is definitely running. 

I can SSH into the EC2 instance. Using curl and localhost does work.

Can you advise, please?

**Comment by gregelin** [comment]
@medined Is your question regarding the `--bind` and "Bad Request (400)" still relevant? Or did it all get fixed?

**Comment by medined** [comment]
I am no longer using the govready software. I'll close the ticket .
