### ISSUE TITLE
Instructions for rendering result of multiple-choice question needs more detail

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#315]
The instructions in https://github.com/GovReady/govready-q/blob/master/Schema.md for how to work with and render results of multiple-choice questions in output needs more detail than is provided. 

For example, the following `{% for ... in .. %} ... {% endfor %}`  when used in the output of a component app module throws an error of `There was an error executing the template questions output document ssp_nist80053r4_AT_3: ModuleQuestion has no module.`:

```
    {% for item in system_admin_security_training_examples %}
      * {{item}}
    {% endfor %}
```

**Comment by JoshData** [comment]
Greg also says that "{{....text|lower}}" isn't working either.
