### ISSUE TITLE
Unanswered questions in questions.yaml cause template error but not in app.yaml

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#319]
While experimenting with template inclusion, I discovered that parameters from unanswered questions found in compliance app's `app.yaml` file are nicely displayed in a top level compliance app's rendered templates (e.g., `<Review frequency>`).

However, if the `app.yaml` output template instead calls an entire output template from a lower level module (e.g., from `questions.yaml` output template), then an error is caused in the top level app output template with message `Template Error: output document ssp_nist80053r4_XX_# in questions could not be rendered: The question is not answered.`

As soon as one question is answered within the module, the error goes away and parameters from unanswered questions in the module yaml file are nicely displayed in the top level compliance app's rendered templates.

Summarizing, it seems necessary to answer at least one question at the module level if the output is delegated all the way to the module yaml file, but not necessary if delegated just to the `app.yaml` file.

Is this behavior fixed?

**Comment by gregelin** [comment]
This is also an issue because the error message does not indicate, nor give the user a link indicating what app needs to be answered.

**Comment by JoshData** [comment]
I'm going to post a PR that just makes it work, without anything dramatic about starting Tasks when apps are started.

**Comment by gregelin** [comment]
We fixed this with PR #320 correct? Can we close?

**Comment by JoshData** [comment]
Yes, you already closed it. 😁
