### ISSUE TITLE
Review django-database-storage update

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#324]
`requirements_txt_checker.sh` found an out of date package. I've added the package to ignore file in order to enable tests to pass. But this package needs to be reviewed and updated.

```
Some packages are out of date:

Package                 Version Latest Type 
----------------------- ------- ------ -----
django-database-storage 0.0.1   0.1.2  sdist
```

**Comment by JoshData** [comment]
Didn't realize there was an issue specific for this. As I noted in #325-

The django-database-storage issue was actually a problem in CircleCI's cache. It was pulling in the wrong package (maybe I had mis-specified the package name in an earlier commit?). Doing a Rebuild without Cache fixed it.
