### ISSUE TITLE
"Chrome failed to start: crashed" in selenium tests in Docker

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#334]
When running `manage.py test siteapp`, Python tries to fire up selenium/chromium.  There's a wait of a minute or two, then the tests crash with the error, "Chrome failed to start: crashed".  See [example stack dump](https://github.com/GovReady/govready-q/files/1469040/python-selenium-chrome-crash.txt).

I tried several fixes and incantations from web searches; none worked.  Current workaround for Jenkins is to avoid running the siteapp tests.

Environment: Docker `python:3` container, which is built on Debian 8.  Docker host is macOS `10.12.6 (16G29)`.

**Comment by gregelin** [comment]
Closed due to age.
