### ISSUE TITLE
Need a way to migrate compliance app structure similar to `manage.py migrate`

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#343]
We will need a way to migrate compliance apps data structures in the database similar to Django's `manage.py migrate` or we run the risk of future users encountering an error of a class similar to `app.png is not an asset.` I am encountering on on an older compliance app I have running locally on my laptop.

The cause of the error is understandable and inconsequential at this stage. We standardized the name for the app's icon when we made the last round of improvements to the apps. We're still early in development of apps. No big deal.

But because the app is loaded into the database and contains user data, I don't have an easy way to fix the error; nor do I have an easy way to export the data. 

Going forward, we will need to version app schemas, test published compliance apps for conforming with schemas, and test code for impact on earlier versions of schemas. Another supply chain to manage.

Here is the full error:

```
Request Method: | GET
-- | --
http://dnfsb.localhost:8000/projects/folders/9/dnfsbgov
1.10.8
ValueError
app.png is not an asset.
/codedata/code/govready-q-apps/guidedmodules/models.py in get_static_asset_image_data_url, line 457
/Library/Frameworks/Python.framework/Versions/3.5/bin/python3
3.5.0
['/codedata/code/govready-q-apps',  '/Library/Frameworks/Python.framework/Versions/3.5/lib/python35.zip',  '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5',  '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/plat-darwin',  '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/lib-dynload',  '/Users/greg/Library/Python/3.5/lib/python/site-packages',  '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages',  '/codedata/code/compliancelib-python',  '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/dnspython-1.16.0-py3.5.egg',  '/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/site-packages/newrelic-2.74.0.54']
Wed, 22 Nov 2017 12:24:43 +0000
```

**Comment by JoshData** [comment]
If this was a really old app the problem has already been fixed. Assets are versioned in the DB along with the schema.

**Comment by gregelin** [comment]
I just ran `python3 manage.py migrate` on my laptop and received:

```
Operations to perform:
  Apply all migrations: account, admin, auth, contenttypes, dbstorage, discussion, guidedmodules, notifications, sessions, siteapp, sites, socialaccount
Running migrations:
  No migrations to apply.
  Your models have changes that are not yet reflected in a migration, and so won't be applied.
  Run 'manage.py makemigrations' to make new migrations, and then re-run 'manage.py migrate' to apply them.
```
This is my main local version of GovReady-Q repo. I have not changed any models locally and I'm up to date with master. I should not have to create any migrations, unless there are some migrations that have been made in master that are not reflected yet.

**Comment by JoshData** [comment]
That's safe to ignore right now. 

On November 22, 2017 8:09:11 AM EST, Greg Elin <notifications@github.com> wrote:
>I just ran `python3 manage.py migrate` on my laptop and received:
>
>```
>Operations to perform:
>Apply all migrations: account, admin, auth, contenttypes, dbstorage,
>discussion, guidedmodules, notifications, sessions, siteapp, sites,
>socialaccount
>Running migrations:
>  No migrations to apply.
>Your models have changes that are not yet reflected in a migration, and
>so won't be applied.
>Run 'manage.py makemigrations' to make new migrations, and then re-run
>'manage.py migrate' to apply them.
>```
>This is my main local version of GovReady-Q repo. I have not changed
>any models locally and I'm up to date with master. I should not have to
>create any migrations, unless there are some migrations that have been
>made in master that are not reflected yet.
>
>-- 
>You are receiving this because you were assigned.
>Reply to this email directly or view it on GitHub:
>https://github.com/GovReady/govready-q/issues/343#issuecomment-346345381

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by gregelin** [comment]
Decided strategy for app migration management in April, 2018.
