### ISSUE TITLE
Do not include hosts (/mnt/apps) source in install scripts for CentOS, RHEL.

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#354]
The sample appsource and the hosts appsource (/mnt/apps) were loaded automatically through standard install because we put it Docker. However, when installing directly on RHEL or CentOS, the /mnt/apps directory does not exist and that causes a server 500 error when going to the store. Deleting the hosts (/mnt/apps) appsource removes the error.

Fix is to make sure that /mnt/apps app source is not installed by scripts that are not on Docker. Alternatively, correct the path on the RHEL and CentOS.

**Comment by JoshData** [comment]
This happened because I ran the first_run script manually to create the initial user and org and forgot that the first_run script also creates appsources. https://github.com/GovReady/govready-q/blob/master/deployment/rhel/README.md#creating-the-first-user

**Comment by JoshData** [comment]
Fixed by e15aaabcb1fb7b14e09eef8b9c2f1ac140691585.
