### ISSUE TITLE
Our docker deployment has Django DEBUG on and uses runserver

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#355]
Our docker deployment is using Django's DEBUG mode, which is nice for debugging site errors but should be turned off if the container is being used in production. But in order to turn it off, we need to add static file serving, which Django only does for us in DEBUG mode. (In other deployments static files are the responsibility of the HTTP server.)

**Comment by JoshData** [comment]
We should also not be using `manage.py runserver` for a production environment.

**Comment by gregelin** [comment]
Fixed commit 5d11366125f54984239c5c8091ec6ca47b9d97b4
