### ISSUE TITLE
Make header checking a settings with default to off

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#361]
We currently have a check for HTTP headers and host name that is causing an error when individuals instantiate Q in more exotic infrastructure as code scenarios like Mesos where the name of the host may not be available to Q configuration files prior to the instantiation of the Q server instance.

The check is a security best practice for in sub-domained multit-tenant apps.

- [ ] Look into reason for the security best practice
- [ ] Make header check into a configuration setting
- [ ] Have configuration setting set to off for most deployments (like Docker) which we think will be single-tenant installs

**Comment by JoshData** [comment]
We decided not to do this because of the security implications of trusting the host header.
