### ISSUE TITLE
Remove yellow "set up your account settings" message

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#364]
The set up account settings message is distracting and people first trying GovReady don't need to be forced to do it. It's distracting when spinning up the C-A-T

**Comment by JoshData** [comment]
Is this about demos or about a better overall user experience?

**Comment by gregelin** [comment]
This change is about both demos and overall user experiences. Increasingly, demos will show the landing page and "first run" experiences by developers see the landing page.
