### ISSUE TITLE
"Compliance Dashboard" modifications

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#365]
As a user who frequently starts new orgs and Q instances, I would like to have more streamlined and useful landing page. Remove elements not being used:

- [ ] Remove "Complete your organization profile" section
- [ ] Remove "Invite collaborators to work with you" - I'm just trying to set up my first app after all

**Comment by JoshData** [comment]
If this is just about making clearer demos, maybe we need some initialization scripts to fill in a default user profile for you?

**Comment by gregelin** [comment]
Making cleaner user experiences for where our customers are currently.
