### ISSUE TITLE
ability to reuse tasks as answers to questions

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#383]
If a user starts an app and adds it to a folder, but then wants that app to be an answer to a top-level question in another app, there's no way to do that. We discussed adding a list of existing tasks to the top of the compliance store that the user can choose from, with each task being able to either link it or deep clone it or shallow clone it... but of course these distinctions are difficult for users to understand.

We also discussed that the question for the user isn't about linking or cloning per se but about whether further changes to the app should affect previously done work that the user might consider archived (e.g. the old SSP). Or we may support archiving through a specific archive action that records a snapshot of a project. We could also consider adding a boolean flag to projects to make them read-only and propagate that to all tasks within it.

**Comment by gregelin** [comment]
Closed due to age.
