### ISSUE TITLE
SELinux httpd_can_network_connect needs to be re-set on reboot

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#389]
After rebooting an SELinux-enabled machine, `setsebool httpd_can_network_connect true` needs to be re-run.

see https://github.com/GovReady/govready-q/blob/master/deployment/rhel/README.md

**Comment by JoshData** [comment]
Also httpd and supervisord may not be running on reboot and should be explicitly configured to come up again in our docs.

**Comment by gregelin** [comment]
OBE
