### ISSUE TITLE
release process improvements (Part 1)

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#395]
* the release script (currently docker_image_build.sh) should fetch & check that the tag is present on the origin remote and is not simply a local tag
* the release script's warnings should be more prominent
* the `RUN ./fetch-vendor-resources.sh` step is cached by the docker build process even though the file content has changed?
* nightlies don't have a VERSION file - have CircleCI kick off the build script to generate and deploy new images to the Docker hub based on master or another branch
* use [PEP 440](https://www.python.org/dev/peps/pep-0440/) version numbers which can be parsed with pkg_resources.parse_version.

**Comment by gregelin** [comment]
@JoshData I think you have  you completed some/all of these release process improvements...

**Comment by JoshData** [comment]
Some yes: checking the tag is on the remote, checking PEP 440 version numbers.

Still to do: CircleCI nightlies need version numbers, maybe? And I didn't make the release scripts warnings more prominent.

**Comment by gregelin** [comment]
Closing this issue and starting further improvements to release process in ticket #487
