### ISSUE TITLE
Help squad invitations don't generate notifications

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#428]
While looking at the Help Squad feature, I noticed that we were sending email invitations to the help squad members to join a discussion but we weren't sending notifications. That's because we don't have a nice way, at this time, to create a notification that brings the user to an invitation (which, in this case, on acceptance adds the user to a discussion).

This raises a larger issue about the relationship between invitations and notifications. All invitations to registered users should generate a notification. Notifications already generate their own emails. Invitations also generate emails. So we'd send two emails if we issued a notification for an invitation.

**Comment by gregelin** [comment]
What if the Help Squad was automatically added to every project (and discussion) b/c they were the help squad? Would we then be able to simply generate a notification and let the notification generate the email?

**Comment by JoshData** [comment]
Yes I think so. (Good idea.)

**Comment by gregelin** [comment]
@JoshData I think you fixed this with the settings page and help squad generates notifications now?

**Comment by JoshData** [comment]
I remember fixing this but I don't see it in the code, so I will have to review further.

**Comment by gregelin** [comment]
Closed due to age.
