### ISSUE TITLE
Unable to view, delete created app instance with non-existance icon name

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#450]
While working on authoring an top level app, I added a module (POAM) and it contained `icon: poam.png`. Icon file is `assets/app.png`.

After loading the top level app from store, I went to view app and received crashing error that asset did not exist. I am unable to launch app in order to delete the app since deleting app can only happen from within app.

**Comment by JoshData** [comment]
I couldn't reproduce this so you'll have to show me.

**Comment by gregelin** [comment]
I tried to replicate by misnaming the `assets/app.png` file in the rules-of-behavior app, but could not.

However, this is the error I am getting in local instance for some older top level apps I loaded.

![screen shot 2018-04-15 at 6 08 07 am](https://user-images.githubusercontent.com/24979/38777834-1c337a06-4074-11e8-81f2-58752ede712b.png)

**Comment by gregelin** [comment]
Fixed long ago.
