### ISSUE TITLE
what happens when a user does not know how to answer a question

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#48]
Josh says: Not being able to skip pushes us to think about the question design. If the user gets to a confusing question, it means we didn't ask the right questions before hand. Like a pre-question that's yes/no about whether they are the right person to ask the next question.

Greg says: But we can't anticipate, and we will make mistakes in our question design, and so we have to handle the use case where a user really doesn't known.
- Answering with some sort of null/NA.
- Mark a question as not-sure.
- Skipping a question.
- Going back to a previous question and answering it differently.
- Skip but you only get three passes. That's nice for forcing modules to not be _that_ bad. Also makes sure users are really trying.
- Having a way to pass is a way to prevent users from putting bad data into form fields like "I don't know."

**Comment by gregelin** [comment]
Addressed this item with v0.8.1. Replace the "Skip" button with I don't know, It doesn't apply, I'll come back, and Not sure. Commit 44f7b2724a52966102a7dee9f40f246de2fc3adf

cc: @JoshData
