### ISSUE TITLE
Links aren't all working on ReadTheDocs

### ISSUE THREAD

**Issue by JoshData** [GovReady/govready-q#497]
There's something funky with links here:

![image](https://user-images.githubusercontent.com/445875/39269783-cb2dc28e-48a1-11e8-9223-cebe509b8a4b.png)

The raw markdown is showing.

http://govready-q.readthedocs.io/en/latest/deploy_docker.html

**Comment by gregelin** [comment]
Seems both the rendering of `inline code` and some links are breaking. Not sure why. Replacing bullets with whole paragraphs.

**Comment by gregelin** [comment]
Links still are not rendering correctly. I think there is an issue with a link to an anchor in markdown going through `mr2` library that is failing.

**Comment by gregelin** [comment]
Fixed in #581
