### ISSUE TITLE
Centos Install "Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt'"

### ISSUE THREAD

**Issue by efraser82** [GovReady/govready-q#523]
pip3 is up to date:

pip in /usr/lib/python3.4/site-packages/pip-10.0.1-py3.4.egg (10.0.1)

but once I put in the next command:

sudo su govready-q
cd
git clone https://github.com/govready/govready-q
cd govready-q
git checkout {choose the tag for the current released version}
pip3 install --user -r requirements.txt
./fetch-vendor-resources.sh

I get an error message of:

Could not open requirements file: [Errno 2] No such file or directory: 'requirements.txt

I went ahead and uninstalled and reinstalled pip3 and still the same results. 
Please advise why I might be getting this error.

Thanks!

**Comment by gregelin** [comment]
Closed due to age.
