### ISSUE TITLE
Inconsistent use of circle-R for "GovReady PBC" in documentation

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#552]
There are mixed instances of "GovReady PBC" on the one hand and "GovReady® PBC" on the other in the docs.  We should choose one and use it consistently, or perhaps, create a style guide rule that, e.g., the circle-R is used once per page at the first instance of "GovReady PBC", or that it's only used in a colophon, etc..

Files to check (at present; re-grep/review when working this issue):

> source/Apps.md
> source/AppSources.md
> source/conf.py
> source/DataDesign_guidedmodules.md
> source/introduction.md

N.B., by the way -- to make it through Sphinx, the circle-R needs to be the literal Unicode character "®" -- i.e., the HTML entity `&reg;` won't work.

**Comment by gregelin** [comment]
Thanks. We should remove all (r) in documents at this time.

**Comment by peterkaminski** [comment]
Fixed in PR #556.
