### ISSUE TITLE
Create OS-independent pre-install prerequisite checker

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#580]
As a developer installing Govready-Q, I want the process to be painless and gotchas avoided. It would be nice to run a script and see if I need to make any OS-level changes to avoid gotchas.

Can I install Q? What will happen when I do? What will change?

**Comment by ethankaminski** [comment]
Some technical notes on how this might be implemented:

For it to be maximally portable, bootstrapping with POSIX-compatible sh code would be ideal (that covers everything other than Windows). A sensible first check would be to verify whether `python3` exists; and if not, whether `python --version` indicates version 3.

If Python 3 **is** available, then we can switch to logic written in Python 3 (if desired, at least; it might be sensible to have some more checks written in sh).

If Python 3 is **not** available, then there's a fundamental unmet prerequisite, and it should be safe to abort at this point (although, if additional checks *have* been written in sh, then those could also be run).

**Comment by gregelin** [comment]
Closed due to age.
