### ISSUE TITLE
Develop automated tests for install

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#582]
It would be great to develop a testing pipeline specifically for testing installs of GovReady-Q on various OSes. Even though we live in a world of containers, we still need to suport Q in various container and non-container configurations.  The install-test runner would be able to fire up environments like CentOS 6 and CentOS 7 and Ubunto 14.x and Ubuntu 16.x and run installation and/or deployment tools.

We might want to look at some of Netflicks and others SRE and Chaos engineering tools for this.

**Comment by ethankaminski** [comment]
Some of the groundwork needed for this would also be useful while I'm working on double-checking the Q install instructions. I'll probably end up setting up something that can be reused for this task (at least for the subcase of testing Linux from a Linux-based host system).

VirtualBox is an obvious possibility, but actually looks unsuitable; it would only work on a host OS, not on a VPS or cloud server.

QEMU would work, but will likely be a bit slower to run. This might be a good fallback option, and would allow for cross-OS testing even under virtualization.

Docker seems like a pretty good bet, at least for testing Linux installs on a Linux-based build/test server. It seems reasonable to assume that Q won't need a special kernel version, so this should work for testing the various Linuxes (Ubuntu/CentOS/Debian/etc).

**Comment by gregelin** [comment]
OBE and containerized version.
