### ISSUE TITLE
Better documentation of required libraries for each OS

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#583]
Document clearly and track the different libraries for each OS that the software packages depend upon.

**Comment by peterkaminski** [comment]
Also see #581.

**Comment by peterkaminski** [comment]
For macOS, specifically determine if mysql libraries of some kind for python are needed, even if Q is not run on mysql.  To test this, you'd have to make sure that any pre-installed mysql libraries do not give you the false impression that they aren't required; i.e., make sure to document what would be needed on a fresh Mac.
