### ISSUE TITLE
Python version in CentOS instructions doesn't work (too old?)

### ISSUE THREAD

**Issue by ethankaminski** [GovReady/govready-q#592]
The install instructions say to use `python34` packages in CentOS, but this didn't work when testing the installation process (there was an unmet dependency in the pip modules). `python36` worked fine, so updating the instructions would suffice to resolve this.

**Comment by ethankaminski** [comment]
Looks like this happened in v0.8.5, if that's of note. (probably not, but I happened to see that changelog item while looking for something else)

**Comment by gregelin** [comment]
@ethankaminski Please update instructions to `python36`.
