### ISSUE TITLE
m2r mangles toctree `:maxdepth:` setting in help docs

### ISSUE THREAD

**Issue by ethankaminski** [GovReady/govready-q#602]
m2r inserts an extra newline between the `toctree` line and the `:maxdepth:` setting when generating help docs. This ends up disabling the `:maxdepth:` setting.

**Comment by gregelin** [comment]
@ethankaminski Thoughts on what we can do? Are you thinking we need to move away from `.md` files to another  markdown format?

**Comment by ethankaminski** [comment]
This looks like either a parser bug or a parser limitation, so the format isn't necessarily the issue. Looking at the m2r homepage, it looks like that project _is_ designed for `.md` with `.rst`-style code mixed in, so our usage should be in scope of m2r. Based on that, I suspect this would be a bug (rather than a limitation) in either m2r or Sphinx.

As for how to fix the issue on our end: if there were any ability to insert another text-converter into the middle of the conversion pipeline, it would be easy to strip the extra newline. We could also switch certain files to `.rst`, and use the `mdinclude` directive if we need to mix a toctree and some markdown in the same file.

There are also various forms of getting the m2r code fixed, such as submitting a patch to their project (probably a sensible thing to do, really), or seeing if we can patch the code on our end (admittedly, that lead to maintenance issues).

**Comment by ethankaminski** [comment]
I just had a quick look at their code, and the issue can be fixed by changing `"\n" + text + "\n"` to `"\n" + text` on (this line of code)[https://github.com/miyakogi/m2r/blob/661a82ccfee48342dcbc3dcca4fd77e6a0a1a900/m2r.py#L510]. It looks like it's actually a bug, too, so I'd say it's worth submitting a pull request to them and seeing if that's accepted.

**Comment by peterkaminski** [comment]
@ethankaminski, good work finding the m2r bug!  Will you submit the bug and patch in their project?

**Comment by ethankaminski** [comment]
Yep, I've opened a [bug report (issue 35)](https://github.com/miyakogi/m2r/issues/35) and a [pull request (pr 36)](https://github.com/miyakogi/m2r/pull/36) in their repo.

**Comment by gregelin** [comment]
@ethankaminski Can we revisit and  and see if working now?

**Comment by gregelin** [comment]
Moved to reStructuredText. No longer relevant.
