### ISSUE TITLE
Variable names rather than values sent in account emails

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#604]
From a Q test system, I received emails that contained URL-encoded variable names rather than the variable values.  I believe these should have been resolved to variable values in the templating engine before being sent.

I don't know yet if this is a configuration problem, or a software problem.

In a password reset email:

plaintext:
`https://TESTDOMAIN.govready.com/accounts/password/reset/key/UNIQUEKEY/ <%7B%7Bpassword_reset_url%7D%7D>`

html:
`<a href="%7B%7Bpassword_reset_url%7D%7D" style="color: #23A">https://TESTDOMAIN.govready.com/accounts/password/reset/key/UNIQUEKEY/</a>`

And in an email address confirmation email:

plaintext:
`https://TESTDOMAIN.govready.com/accounts/confirm-email/UNIQUEKEY/ <%7B%7Bactivate_url%7D%7D>`

html:
`<a href="%7B%7Bactivate_url%7D%7D" style="color: #23A">https://TESTDOMAIN.govready.com/accounts/confirm-email/UNIQUEKEY/</a>`

**Comment by peterkaminski** [comment]
Perhaps this happened because some configuration isn't set up.  If that's the case, the emails _still_ shouldn't have been sent to a user this way; there should have been either an interactive or emailed error message to an admin.

**Comment by JoshData** [comment]
It looks like it's an issue with the conversion of the Markdown email template into plain text, which is done by a library I wrote which calls another library I wrote to turn Markdown into plain text. The problem is probably something to do with escaping of variables within the Markdown.
