### ISSUE TITLE
Convert docs from Markdown to reStructuredText

### ISSUE THREAD

**Issue by ethankaminski** [GovReady/govready-q#606]
In discussion with Pete and Greg, we decided to convert the documentation source from Markdown to reStructuredText, on account of the latter being what Sphinx natively uses. This could be done easily by running the docs through `m2r` (but note issue #602; probably best to patch that locally before converting).

Due to the potential for merge conflicts, and the number of docs changes we plan on pushing through soon, I'd say it's best to do this _after_ most of the other docs changes have settled down. Individual files can still be converted as-needed.

**Comment by gregelin** [comment]
Completed.
