### ISSUE TITLE
Document all environment.json keys, centrally

### ISSUE THREAD

**Issue by ethankaminski** [GovReady/govready-q#607]
The documentation for `environment.json` keys is scattered around various pages (e.g., I only just found `mailgun_api_key` today, in the RHEL/Centos page). A list of all the keys, and what they do, is the sort of thing that should go in the current Environment Settings page.

**Comment by ethankaminski** [comment]
Some handy `grep` commands for this (so I can remember them):

```
# get each top-level key, by itself, no dupes
grep -rP -ho "environment(\.get\(|\[)(['\"])\K.*?(?=\2)" siteapp/ | sort | uniq
```
```
# show key in original context
grep -rnP -o "environment(\.get\(|\[)(['\"])\K.*?(?=\2)" siteapp/
```

**Comment by gregelin** [comment]
This has been completed.
