### ISSUE TITLE
Is Mailgun the only supported service for inbound mail? (documentation inconsistency)

### ISSUE THREAD

**Issue by HeatherSoron** [GovReady/govready-q#609]
I'm not sure what to do with this part of the documentation review, so creating an issue in hopes that someone else will.

On the page for setting up GovReady-Q with Docker, it's stated that Mailgun is the only service supported for inbound mail (which is an important detail that's not mentioned elsewhere):

```
Some of GovReady-Q’s outbound emails can be replied to. When a user replies to a notification of a discussion comment, the reply’s body is post as a new comment on the discussion. Currently we only support an incoming notification hook from Mailgun, and it is not yet configurable for the docker deployment. TODO
```

However, on other pages (like the System Requirements page), it's stated that "for sending email notifications and receiving comments via email", any SMTP server works:

```
Any SMTP mail server (MTA) supporting STARTTLS connections.
```

I'm not sure which is accurate. If it's only Mailgun, then this should be documented more clearly, and outside of just the Docker-specific instructions. If it's any SMTP server, then the Docker instructions need to be updated accordingly.

**Comment by ethankaminski** [comment]
@gregelin I'm not sure how to resolve this issue, so here's a ping based on the assumption that you'll know who to assign it to.

**Comment by gregelin** [comment]
OBE
