### ISSUE TITLE
Develop more test coverage for settings page

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#613]
The settings page needs additional tests. Only a starter set of tests has been put in place in `siteapp.tests.OrganizationSettingsTests`.

**Comment by gregelin** [comment]
See PR #610 for when `siteapp.tests.OrganizationSettingsTests` were first added. Same PR also has some changes made to organization settings page to support the assignment of organization administrators.

**Comment by ethankaminski** [comment]
Commit dc4b4afeed, right?

@gregelin also, for planning purposes, what's the relative priority on this vs. the docs cleanup project?

**Comment by davidpofo** [comment]
Addressed in [dc4b4af](https://github.com/GovReady/govready-q/commit/dc4b4afeedf33578951932a8bbba6f92eb1b1983)
