### ISSUE TITLE
first_run is silent when it doesn't create an admin user

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#626]
What happened:

* I deployed [GovReady-Q with Docker](https://govready-q.readthedocs.io/en/latest/deploy_docker.html).
* I caused the `first_run` script to run non-interactively (with something similar to this, but I'm not sure exactly how):

```
./docker_container_run.sh --bind 172.30.0.208:8000 --address 18.223.206.38:8000 --dburl postgres://$DBUSER:$DBPASSWORD@$DBHOST/$DBDATABASE -- -e FIRST_RUN=1
```

* I failed to note the resulting admin user/password
* I ran the `first_run` script again in several different ways, e.g.:
  * with the same database, but a brand new container
  * by starting a shell on the container, and executing `first_run`

Subsequent runs of `first_run` in any of these ways would print no output, because `first_run` detects an existing admin user and won't create a new one.

I didn't know I already had an admin user created, and the lack of output confused me -- I didn't know why `first_run` would not create an admin user for me.  I thought it was failing (silently) somehow.

I suggest that `first_run` print a warning message and short explanation when it does not create a user, so it would be clear why it would not create a user.

**Comment by gregelin** [comment]
This was fixed.
