### ISSUE TITLE
govready-apps-dev apps not listed when installed via Source Type Git repo

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#638]
@JoshData  No apps are showing up in the App Source administration page for "govready-apps-dev" added as GitHub HTTPS App Source to Docker container running v0.9.0 built from branch `0.9.0.rc`. Settings:

```
Slug: govready-apps-dev
Source Type: Git Repository over HTTPS (Public Repository)
URL: https://github.com/govReady/govready-apps-dev
Branch: published
```

I did have to change the `catalog.yaml` file because the file was not parsing the tabs beigning the indents.

**Comment by JoshData** [comment]
You need to set `path` to `apps` to match the subdirectory in the repo.

**Comment by gregelin** [comment]
Reviewed issue further and tested files. Discussed with @JoshData. The `catalog.yaml` file is not used with GovReady-Q 0.9.0.
