### ISSUE TITLE
Merge pk-nginx-20190605 into 0.9.0.dev

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#643]
The Q+nginx branch `pk-nginx-20190605` is done, including docs.  Merge the `pk-nginx-20190605` branch into `0.9.0.dev` to add it to the 0.9.0 release.

**Comment by gregelin** [comment]
@ethankaminski Can you please test these instructions to make sure they work?

https://github.com/GovReady/govready-q/tree/pk-nginx-20190605/deployment/docker-compose-nginx

**Comment by ethankaminski** [comment]
Can do, probably in several hours.

**Comment by gregelin** [comment]
Merged.
