### ISSUE TITLE
Expand on /etc/hosts instructions in "GovReady-Q and nginx via Docker Compose" doc

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#646]
In the doc "GovReady-Q and nginx via Docker Compose" (which is the `pk-nginx-20190605` branch, in `deployment/docker-compose-nginx/README.md`), in the "GovReady-Q Is Up" section, we give the instruction "edit your /etc/hosts file and add this line".

This is a hard instruction for a non-technical user.  Try to find either more explanation about editing /etc/hosts (sudo on a mac, whatever privileges are needed on windows, etc.), or maybe use the hostname `localhost` (which would require specifying the hostname, see the "Specify Parameters" section), etc.

**Comment by gregelin** [comment]
Closing this issue because I think only technical users will be working with docker and docker compose.
