### ISSUE TITLE
IE and Chrome on Windows cannot navigate to a DEMO PTA question "2f other SPII"

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#670]
IE 11 and Chrome and Windows fails to display the error message "This question cannot currently be answered or skipped because its value is currently being imputed or it is dependent on questions that have not yet been answered." for question that is dependent on another question that displays. 

When J tried to jump to question "2f other SPII" in Demo PTA, he was routed back to the first question. However, I was able to access "2f other SPII". Even when the previous question is answered, there is a problem access "2f other SPII" on IE and Chrome on Windows.

<img width="1401" alt="Screen Shot 2019-07-22 at 11 39 57 AM" src="https://user-images.githubusercontent.com/24979/61646204-b0923100-ac76-11e9-82dd-bdca5a6c9112.png">

**Comment by davidpofo** [comment]
Windows users will be using WSL 2 or docker so I can't imagine this is still an issue.
