### ISSUE TITLE
checksum changed for siteapp/static/vendor/google-fonts.css

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#674]
`fetch-vendor-resources.sh` does checksums against the assets it downloads.

At commit `2dc0e22271af33d66e3f52428f8b07733b414d7a`, the checksum for `siteapp/static/vendor/google-fonts.css` was found to have changed from:

`d36dbb50dcb3932ce7e3a0271d29eb6d95b82efd6ba08044f2570d9e337f5a88`

to:

`990e7373d100faee6fa7d92c1277695520e3c502f726bb28ce03d2b6d2cd3e6c`

This is probably because of a benign update, but it could also indicate introduction of a vulnerability.  For instance, custom web fonts have been known to be used for infiltration, e.g., https://www.bleepingcomputer.com/news/security/new-phishing-tactic-uses-custom-web-fonts-to-prevent-detection/

To clear this issue:

* check that the incoming CSS file, and its linked WOFF/WOFF2 files, are clean
* check that the `google-font-download` script that is used to download the assets is clean

Also, consider archiving old versions of the assets downloaded by `fetch-vendor-resources.sh`, to enable easy `diff` runs against old and new versions of the assets.

**Comment by gregelin** [comment]
Issue has been addressed.
