### ISSUE TITLE
Answer the next available question after the most recently answered question

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#677]
As a user who skips ahead, I want to continue to move forward in the questionnaire to the next question after the question I just answered instead of popping backward to the top of the queue of answered questions.

**Comment by gregelin** [comment]
@JoshData Can you provide any direction on this? Can enhance to the `walk_module_questions` to connect to track a spot within the queue that begins with an indicated value?

**Comment by JoshData** [comment]
The best thing might be to delete the function and start over with new logic about how to proceed through questions. The logic made more sense early on when we considered the questions to be an unordered dependency tree, but these days Q treats them essentially as ordered by their order in the YAML file.

**Comment by gregelin** [comment]
Fixed in b21e8145b2a17eb81dc2c84f14338d3a85ad5903
