### ISSUE TITLE
PEM files cause indigestion

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#714]
Background: In 0.9.0, we have a generic self-signed PKI keypair in `/deployment/docker-compose-nginx/nginx/*.pem`.

In some users' environments, the PEM files may be caught by scanners or filters as potentially important and private secrets and cause problems.

Suggested fix:
* move the keypair to a web-accessible location
* change `/deployment/docker-compose-nginx/README.md` to include steps to retrieve the keypair

Other possible fixes:
* find and use a well-known generic keypair instead
* direct the user to create their own self-signed keypair with openssl

**Comment by gregelin** [comment]
Removed self-generated PKI files from repo.
