### ISSUE TITLE
need 'project.has_write_priv(user)'

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#719]
During the transition between 0.8.6 and 0.9.0, we noticed there isn't a `project.has_write_priv(user)` method in `guidedmodules/models.py`, but we probably want one.  We would also have to create UI in order to set these permissions.  See https://github.com/GovReady/govready-q/pull/718#pullrequestreview-282165641 (click "show resolved")

**Comment by gregelin** [comment]
Fixed in #720.
