### ISSUE TITLE
"and we're done" occasionally is not rendered in the sidebar

### ISSUE THREAD

**Issue by cityinohio2019** [GovReady/govready-q#748]
There are a couple of instances within a module when the "and we're done" is not being rendered. It is being rendered in the HTML source code. Here is a screenshot, dude.
![Screen Shot 2019-09-20 at 3 57 23 PM](https://user-images.githubusercontent.com/50302989/65355298-a1b8f380-dbbf-11e9-8075-cf460cc5f23d.png)

**Comment by gregelin** [comment]
Solution is to scroll page; "and we're done" is being rendered but it is "below the fold." It is not apparent to user to scroll. A better solution would be to have "and we're done" always displayed and the scroll be just for the number of questions.

**Comment by gregelin** [comment]
False positive. Link was hidden below the fold.
