### ISSUE TITLE
Tables do not seem to display in Markdown templates

### ISSUE THREAD

**Issue by gregelin** [GovReady/govready-q#79]
Using markdown syntax for tables does not appear to generate tables in templates.

**Comment by JoshData** [comment]
Adding that [Github Flavored Markdown](https://github.github.com/gfm/) supports tables, but last I checked there's only a C implementation of it. And it doesn't support multi-line (block-level) content within table cells.

**Comment by JoshData** [comment]
Greg reports that HTML tables in Markdown aren't exporting to Word (in our new download feature) properly. Probably the same with the new Markdown tables.

**Comment by JoshData** [comment]
Schema.md talks about tables but doesn't show the new table syntax.

**Comment by gregelin** [comment]
Support for better tables in output document templates using our new table rendering library extension to CommonMark-py in commit c39d213a4cc77aea163a13b16488cabf1a8a32f4
