### ISSUE TITLE
(0.9.0) Server Error (500) - NoneType object has no attribute 'get'

### ISSUE THREAD

**Issue by bashscr** [GovReady/govready-q#808]
Install Type: Docker
Version: 0.9.0 / 0.9.1
Using the latest Docker from Docker Hub on a Windows & Mac OS, image digest: “6909cf370f20”, we are running into an internal Server Error (500) when trying to add an App Source.
 
![image](https://user-images.githubusercontent.com/51954831/76894525-b02d5280-6864-11ea-80e0-f5b721469174.png)

Action taken: Executing the “docker container exec govready-q tail_logs” command, this is the output from the logs:
![image](https://user-images.githubusercontent.com/51954831/76894537-b6233380-6864-11ea-8916-b7abec135877.png)
 
Additionally:
![image](https://user-images.githubusercontent.com/51954831/76894550-bb807e00-6864-11ea-9694-5332ec4d5ea9.png)
 
Expected result: Being able to add the app source from the repo: github.com/GovReady/govready-apps-dev

**Comment by gregelin** [comment]
@bashscr This should now be fixed. Testing now...

**Comment by gregelin** [comment]
Fix in PRs 150083f0cc14a7ee16be8a2c82ef63ed26fd4e7c, 14dc7582bafed64c1e18cc5a3636e6222d9745c7, 157a5ac1445570715a11360b27ddb3c0fb37dd3a

**Comment by gregelin** [comment]
@bashscr Issue fixed in branch `master`.

**Comment by bashscr** [comment]
Thanks, LGTM.

**Comment by gregelin** [comment]
@bashscr Excellent!
