### ISSUE TITLE
(0.9.1) There was an error executing the template 'ssp' output document

### ISSUE THREAD

**Issue by bashscr** [GovReady/govready-q#818]
Install Type: Docker
Version: 0.9.1
Using the latest Docker from Docker Hub on Windows OS, we are running into an error after filling out the questionnaire for generating an SSP. The answers supplied were randomly entered.
 
![image](https://user-images.githubusercontent.com/51954831/77570088-9f529180-6ea1-11ea-8827-a13ffb4a0f53.png)

Action taken: Clicking the "Preview Draft SSP"

Expected action: The Preview Draft SSP document will appear with the information supplied from the questionnaire.

**Comment by gregelin** [comment]
@bashscr Fixed in version 9.1.3.
We corrected error handling of new Datagrid question type. See PR #816.
