### ISSUE TITLE
Docs Issues

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#848]
### broken links on https://govready-q.readthedocs.io/en/latest/Environment.html

example:
![Environment_Settings_—_GovReady-Q_Compliance_Server_0_9_1_3_documentation](https://user-images.githubusercontent.com/169442/81318386-09368d00-9043-11ea-9d2a-49d39ca36fc6.png)

### broken boxes on https://govready-q.readthedocs.io/en/latest/introduction.html

example:
![About_GovReady-Q_—_GovReady-Q_Compliance_Server_0_9_1_3_documentation](https://user-images.githubusercontent.com/169442/81317628-eeafe400-9041-11ea-846e-53f062e82de6.png)

## Other errors

* Do a full build (e.g., after `rm -rf docs/build/*`) to see additional errors.

* Pete experienced [problems with Sphinx 3.0.0](https://github.com/sphinx-doc/sphinx/issues/7420), and was successful with Sphinx 2.4.4.  Consider trying different Sphinx version if you have problems finding/fixing errors.

**Comment by gregelin** [comment]
No longer relevant after fall 2020 documentation refactoring
