### ISSUE TITLE
MySql installation problem on Ubuntu 20.04

### ISSUE THREAD

**Issue by peterkaminski** [GovReady/govready-q#910]
Following the Ubuntu install instructions on Ubuntu 20.04 (as of May 1, 2020) results in an error, "dpkg: dependency problems prevent configuration of mysql-server".

Ubuntu 20.04 was on AWS, ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20200423 (us-west-2 ami-09dd2e08d601bff67)

Here is a screenshot from the docs:

![mysql-install-docs](https://user-images.githubusercontent.com/169442/83584966-797ae600-a4fd-11ea-9767-c10d7e0d9bbe.png)

Here is the dpkg error:

![dpkg-error](https://user-images.githubusercontent.com/169442/83584978-80a1f400-a4fd-11ea-913e-05f2a3ef5c76.png)

**Comment by gregelin** [comment]
See related issue #1084.

**Comment by davidpofo** [comment]
addressed in [govready-q-docs](https://github.com/GovReady/govready-q-docs/pull/20)
